### ISSUE TITLE
Add basic log4j implementation to the JFiles project

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#1]
Add Log4J to team2 branch.  Version 2.6.2 should be used unless we find a reason not to.

**Comment by bdenlinger** [comment]
See [commit](https://github.com/rsanchez-wsu/jfiles/commit/7b501567f71daa048df0b9424a082b249fefcd51).

**Comment by rsanchez-wsu** [comment]
Commit reference: 7b501567f71daa048df0b9424a082b249fefcd51
