### ISSUE TITLE
Client Can Send a File to the Server

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#100]
This function should be nearly identical to that of the server's file sending function. Upon a certain entered command, the client should be able to retrieve a file from it's local directory, retrieve the bytes, and put them into the output stream on its way to the server. This issue can be considered finished when the client can at least read bytes from a file and correctly put them on the output stream to the server. Whether the initial implementation is hardcoded or accepts arguments is up to the programmer.

**Comment by rsanchez-wsu** [comment]
@joyceje What was the rationale for closing this issue? Was it completed? If so, how? If not, why/how was the decision made to close and what is the follow-on plan if any?

In this case there is a commit (68bd68a) associated with this issue, but that commit's message only references this issue, it does not claim to fix it.  If the commit in fact fixes this issue, then a comment should have been made along with the closure to indicate that.
