### ISSUE TITLE
Server Can Receive File from Client

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#101]
This issue is the direct counterpart of #100. The server needs to have a function where it can accept a stream of bytes from the client side and create a file in the form of "filename-copy.txt". Ideally, this should be its own method like the server's file send command. To solve this issue, the server needs to be able to accept a stream of bytes from the input stream and then write them to a file. This issue can be worked independently of #100 since it only focuses on the server functionality.

**Comment by rsanchez-wsu** [comment]
@joyceje What was the rationale for closing this issue? Was it completed? If so, how? If not, why/how was the decision made to close and what is the follow-on plan if any?

Does commit (c87db1b) close this issue?  If so, then please state that explicitly.  The message for that commit only references this issue without claiming to fix it.
