### ISSUE TITLE
Implement Checksum on Sending Files

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#102]
For this issue, the program needs to be able to attach checksums to files that are sent over the output stream. As our program stands at the time of this writing, a checksum is only attached to the received file. For this issue, we must figure out how to read the input stream and find the part of it that contains the checksum value. This issue can be considered solved when we have some way of sending the checksum over the output stream and the receiver can print it to the console or otherwise display that it has received the correct checksum value.

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github I like this idea.  I would be interested to hear some specifics for different approaches to attaching the checksum to the file.  I have one that I like, but I want to hear other ideas first before I toss mine out there.

**Comment by rsanchez-wsu** [comment]
@joyceje What was the rationale for closing this issue? Was it completed? If so, how? If not, why/how was the decision made to close and what is the follow-on plan if any?
