### ISSUE TITLE
Write Exit Command

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#103]
While our branch currently implements threads, they are rather limited in functionality. As it stands, the client closes the connection as soon as a single command is entered. We need to implement a loop (do-while?) that can keep the client connected until they enter an exit command. This issue can be considered solved when the client can keep a connection to the server and execute any number of commands until an "exit" command is typed, which will cause the client to properly close the connection.

**Comment by cunningham124** [comment]
@DarthPacer and I hold that there is quit and exit command in the code. The exit command does nothing and the quit command throws an exception. So we are going to remove the quit command the  make the exit command work.

**Comment by DarthPacer** [comment]
@cunningham124 and I have completed this issue. Waiting to close until the commit has been pushed to the team1-dev branch. There are some checkstyle issues in the code, he wanted to address first.

**Comment by rsanchez-wsu** [comment]
@DarthPacer @cunningham124 Nice work.

**Comment by slyr91** [comment]
@DarthPacer @cunningham123 I dont know if you guys changed this or want to utilize this feature in the future but the commands you guys were talking about were located in a switch that did not have a break statement between the exit and quit commands. So even though exit didn't have any code it would flow over from exit into quit where the desired operations would lie. Switch statements keep executing statements until it either hits a break or the end of the switch.
Hope this explanation helps.

**Comment by slyr91** [comment]
Oops meant @cunningham124

**Comment by rsanchez-wsu** [comment]
@joyceje What was the rationale for closing this issue? Was it completed? If so, how? If not, why/how was the decision made to close and what is the follow-on plan if any?

The indication from the comment above by @DarthPacer is that he and @cunningham124 implemented this and then were waiting for the commit to be pushed.  Perhaps that commit did not include a reference to this issue in the message.  If that is the case, the commit should be tracked down and mentioned here to ensure continuity and traceability.
