### ISSUE TITLE
Conforming the GUI to meet JavaBean Criteria

### ISSUE THREAD

**Issue by randymusser** [rsanchez-wsu/jfiles#107]
We will need to ensure that our GUI is serializable, has a public zero argument constructor, and we need to create the appropriate getters and setters.

**Comment by rsanchez-wsu** [comment]
@randymusser That's a fantastic idea and a wonderful set of criteria.  Where did you get such a wonderful idea? :-)

**Comment by cashjason** [comment]
I have pushed my changes to the team 12 branch, but I am having trouble making the file serializable and getting my build to succeed then. That is the last thing to do before making this a javabean

**Comment by rsanchez-wsu** [comment]
@cashjason What is the commit ID that you pushed?  Make sure in the future to include a "Ref #xyz" in your commit message so that GitHub will automatically associate the commit with the issue.

**Comment by rsanchez-wsu** [comment]
The commit id is a8c84df as reported by @cashjason in Slack ( @cashjason , FYI, if you respond in Slack, the comment will not make its way back to GitHub, so please make sure to reply via the appropriate issue/commit/etc. in GitHub so the reply is associated with the right part of the project.)
