### ISSUE TITLE
Create panel to display file path for GUI

### ISSUE THREAD

**Issue by matthews92** [rsanchez-wsu/jfiles#108]
This panel should display the the current location in the file system to the client.
For example: 'C:\Users\Public\Downloads' would be displayed in the panel and it should accurately reflect on which folders and files are in this location by the GUI.

In the future this panel may be switched to be editable by the user to change their location in the file system, but for now it will be unable to be edited by the user.

**Comment by rsanchez-wsu** [comment]
@matthews92 The current location in which filesystem?  The local filesystem or the remote filesystem?

**Comment by matthews92** [comment]
@rsanchez-wsu I was initially thinking the remote system, should this GUI also be working with the local system? I think I might be missing a big picture thing with the functionality.

**Comment by rsanchez-wsu** [comment]
@matthews92 I think we will eventually need both.  Team 1 is working on code that allows transfers in both directions between the server and the client.  I think it makes sense that the client GUI will need to have context for both the location on the server and the location on the client.  You don't have to tackle both right away, but I think they both need to be done eventually.

**Comment by matthews92** [comment]
The area for the file path to be displayed in has been finished and is populated with the initial location, further work could be done to edit it as the user moves locations in the file tree.
