### ISSUE TITLE
Data Structure for Parsed XML Objects

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#113]
Currently our GUI parses XML and stores this data into an array list. However, this only stores a file / folder name and extension. 

i.e. the array list holds test.txt, test, test.png, etc.

This is then iterated through to determine how many objects need to be displayed in the GUI window and the text to display.

This only gives us access to a file name and it's extension, and more information will need to be accessed than this, such as file type (folder vs file).

I believe a good approach to this is a 2D array which will contain an array for each file or folder object and the necessary information for that file / folder. This internal array can then be accessed to gather the additional information needed.

Example:

`[0] 
    => array(
        name = "test",
        extension = ".txt",
        type = "file"
    ),
[1]
    => array(
        name = "folderTest",
        extension = "",
        type = "folder"
    )`

**Comment by bdenlinger** [comment]
This is currently being covered by our JFile bean work and specifically #109 will populate a Map data structure with the [basic file attributes](https://docs.oracle.com/javase/7/docs/api/java/nio/file/attribute/BasicFileAttributeView.html).

The end product of this should be an array of JFile objects that you an iterate through.

**Comment by AlexDespain01** [comment]
@bdenlinger How would I incorporate this into our project?
