### ISSUE TITLE
Import libs and setup DB enviroment

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#114]
The first step is to create a Derby DB is getting the libraries imported into Ivy and setting appropriate classpath parameters.  Consult the [official tutorial](http://db.apache.org/derby/papers/DerbyTut/install_software.html#derby_configure) for steps.
### Completion Goals
- [x] Get Derby jar imported and dependencies in Ivy.
- [x] Set classpath parameters in build environment.

**Comment by DarthPacer** [comment]
I will get my Eclipse environment fixed tonight and begin working on this.

**Comment by DarthPacer** [comment]
Throwing this one back into the pool for someone else to attempt. I have tried to get it imported and it is not cooperating. I am sure this is a user error on my part, however, I know Chris's issue is setting up a database so i believe he is dependent on this and i do not know when Ill be able to work on this again today/tomorrow.

**Comment by tytrip** [comment]
Not sure when this was done but it appears that the derby-10.11.1.1.jar has already been added to the "lib" directory in the JFiles project as well as being added to ivy. Therefore, I am closing this issue.

**Comment by rsanchez-wsu** [comment]
@tytrip I included Derby in the initial project commit to have an Ivy dependency in the project from the start.  I'm sorry I've not been as diligent in monitoring the GitHub traffic in Slack, or I would have pointed this out as soon as the issue was opened.
