### ISSUE TITLE
Create a Derby database for the project

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#115]
We need to create a database and table to store the tag information of each file tagged.  This warrents further discussion on table and DB structure.
### Completion Goals
- [x] Create Derby Database
- [x] Create tables to store data

**Comment by rsanchez-wsu** [comment]
@bdenlinger @Christofo  If I read this correctly, then this issue is blocked by #120 and #121.  Is that right?

**Comment by Christofo** [comment]
@rsanchez-wsu Somewhat, I am about to begin at least creating a Derby database. Obviously no tables will be added until those issues are closed.

**Comment by bdenlinger** [comment]
Working on this with @viro101 .
