### ISSUE TITLE
Create an Errors class to abstract error messages

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#116]
An enum class is needed to abstract the text of the error message from the code.  Currently, error message text is limited by checkstyle line length limits of 100 characters.
### Complete Goal

Create a class similar to [this](https://ceg3120fall2016.slack.com/files/bdenlinger/F2TJT857T/error.txt) that can be used to abstract error text from code.

**Comment by DarthPacer** [comment]
This appears to be done? Closing he issue.
