### ISSUE TITLE
Summarize Chapter 11 of Textbook on Wiki

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#117]
Chapter 11 in the course textbook provides an overview on the use of remote objects in Java. I feel that one of the most efficient ways of getting a feel for this kind of programming is to read over these sections and post summaries to pages on the wiki. It's a way that we can learn while also providing useful information to other students. This issue can be considered finished when we have at least 3-4 different wiki pages on remote objects, each of them ideally summarizing a part of the textbook.

**Comment by Swilloughby-github** [comment]
Summary has been posted.

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github Please provide a link to the wiki content.
