### ISSUE TITLE
Post Outside Research to Wiki

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#118]
Similar to issue #117, we need to do some legwork on getting acquainted with remote objects by doing some of our own research on the topic. The textbook likely provides a good overview, but it would also be helpful to get some sources from outside that scope. Find RELIABLE sources in print or on the web that provide overviews/tutorials of remote objects. Similarly, we should summarize these sources on their own wiki pages, and we can consider this issue closed when we have at least 3-4 wiki pages and unique sources.

**Comment by cunningham124** [comment]
Swilloughby-github Created Wiki pages for: 
RMI Overview
Implementing a Remote Interface
Parameter Passing in Remote Method Invocation
Locating Remote Objects
Remote Server-Client Programs

**Comment by rsanchez-wsu** [comment]
@cunningham124 Please provide links for the wiki pages.
