### ISSUE TITLE
Comment Code to Prepare for Remote Object Implementation

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#119]
This issue will most likely come after the previous two in this milestone. After we have a decent understanding of how remote objects work in the context of JFiles, we need to look over our code and see how they will fit into our current implementation. Write comments over lines that you think will need to be modified/removed to make room for remote objects. If we need to write new methods, provide some base documentation, such as a method name, description, and parameters. The closing condition for this issue is understandably hard to pinpoint, so we should at least aim for the condition where each of our team members has at least made some sort of contribution to the documentation.

**Comment by joyceje** [comment]
Below commits cleaned up the code and made sure it ran in ANT and Clean Bugs
Commit ID: 7be5a4f853c60ca67a093aa269fc211bee8e193c

Commit ID: 066f4dd139f815249801a2702b03ca30ed5779be
