### ISSUE TITLE
T5-M1-I2: Creating the JFileManager Class

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#12]
# T5-M1-I2: Creating the JFileManager Class

> <p>2) Team 5 shall create the skeleton structure for JFileManager, which will manage JFile objects.</p>

<p>This class shall have methods geared towards managing JFiles, such as copy, paste, delete, etc. This class will interact most closely with the JFile class and will require the most collaboration with other teams. Hopefully, this will take security (authorization, authentication, accounting), networking, and file management and be the meeting point of the three. To this end, most of the methods in this class will consist primarily of implementations of other methods and APIs.</p>

<p>This is separate from a JFolder object (which we may want to make later), in that this creates methods that are needed in implementation to manage JFiles, but may not be appropriate for the JFile class itself. It may be made up entirely of static methods and not need instantiation. All interactions between implantation and JFiles should go through this. In other words, this will be the class that unifies the File API and makes it usable by the implementation team.</p>

<p>The documentation shall reflect this. This class must have the following fields, constructors, and methods:</p>

### Fields:

<ul>
 <li>JFile [] clipboard
</ul>

### Constructors:

<ul>
 <li>JFileManager()
</ul>

### Methods:

<ul>
 <li>cut(String location)
 <li>copy(String location)
 <li>paste(String location)
 <li>delete(String location)
 <li>move(String fromLocation, String toLocation)
 <li>rename(String location, String name)
 <li>open(String location)
 <li>openWith(String location, Appliaction app)
 <li>getDetails(String location)
 <li>getType(String location)
</ul>

---

<p>Setting up appropriate return types will be the duty of the individual who is making the methods. Team 5 should discuss how these methods will be implemented before starting actual work on the methods. This is also the duty of the member who is working on the methods.</p>

**Comment by Dorkatron199** [comment]
This will be closed when we finally get Ant working and get this pushed to master. We also will not push this to master until the entire API is at least functional.

**Comment by Dorkatron199** [comment]
@rsanchez-wsu @BrandAllred @srodriguez4 

In regards to Issues #11 and #12, do you want us to just close these issues now and close the milestone, or do you want for us to wait until these classes get pushed to main, which won't be for a very long time? We have both of these classes pushed to team5-dev and will be pushing to team5 soon. These issues are, for all intensive purposes completed, but GitHub doesn't want this to be registered as complete until master sees these changes. (I assume that this is the difference between closses #[number] and fixes #[number].) Additionally, which policy would you like us to use from this moment on? 

Thank you very much for your time.

**Comment by Dorkatron199** [comment]
This issue was finished but the commits didn't close the issue. I am closing it manually.

52e4916 was enough to fix it, and e704a07 should have closed it.

**Comment by rsanchez-wsu** [comment]
@Dorkatron199 For the time being I don't have a strong feeling about whether a change needs to be merged to master before the issue itself is closed.  I am OK with the issues being closed once the fix is committed on any branch.  Given how many issues we have open at any point in time, it would not make sense to force issues to stay open.

I may change my mind on this in the future, but not for now.
