### ISSUE TITLE
Agree on table structure for storing file tags

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#120]
As a team, we need to agree on a table structure to store file tags.
### Completion Goals

Post agreed structure to the team wiki page.

**Comment by DarthPacer** [comment]
Started the wiki page on the file tag data structure, need to have more information from Brian before deciding on the structure as a team.

**Comment by tytrip** [comment]
Is this issue still relevant? Did we decide that we will not be storing tags?

**Comment by DarthPacer** [comment]
I was not sure what the finalized decision was, if we are for sure no longer using tags, then this can be cancelled.

**Comment by rsanchez-wsu** [comment]
@DarthPacer Please provide a link to the wiki page so that it can be easily found from this issue's discussion.

**Comment by Christofo** [comment]
Are users going to have the ability to add custom tags? If so then I suppose a database could be used, if not then I feel we should store usable tags in the config file.

**Comment by Christofo** [comment]
@SasquatchMighty and I have decided to use the tag database for custom tags, we will populate the database with some basic tags that a user can use. The user will also have the ability to create new tags and have them stored in the database.

**Comment by bdenlinger** [comment]
filepath VARCHAR(260) tag VARCHAR(255) makes sense to me.  Just a key value pair of the absolute filepath and a tag.  260 for the filepath size as that is the max Windows file path length.  255 is the max for EXT4.

**Comment by Christofo** [comment]
We will need to update the tags to be in a separate database that is not stored in memory.

**Comment by Christofo** [comment]
The table structure has been added to the wiki.

**Comment by rsanchez-wsu** [comment]
@Christofo Where on the wiki?
