### ISSUE TITLE
Agree on table structure for cacheing directory information

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#121]
Another use of a database is as a caching mechanism for individual directories.  When something is requested from the client, then the cache is checked, anything found there is displayed, then an update is requested from the client.
### Completion Goal
- [x] Post table structure to team wiki
- [x] Work with team 4 regarding command inputs how to integrate cache with their work

**Comment by tytrip** [comment]
@viro101 @kryan100 @thugmunch @ChronoAnomaly @dmaddalena Please take a look at our idea for the caching table (https://github.com/rsanchez-wsu/jfiles/wiki/Caching-Table-Structure) and see how you think we could integrate this into some of your search functionality.

**Comment by kryan100** [comment]
This can be useful if the user is only looking for a single file. I can check the cache first, exiting the search if I find something. So following the structure you posted, the search function will search through the cache using the supplied pattern. Upon finding a file that matches the pattern, the function retrieves the path, constructs a JFile, then ends after passing the JFile to the client to display in the GUI.

**Comment by rsanchez-wsu** [comment]
@kryan100 That sounds good.  I would also add that after rendering/displaying the cached object (if one is found) then it should also make a request of the remote server to update the display and then cache any updated data.

**Comment by bdenlinger** [comment]
My idea:
filepath VARCHAR(260), XML BLOB

Blob is storing the XML previously returned from the server.  I see that Derby has an XML datatype, but I don't see us using the features.

**Comment by tytrip** [comment]
Collaboration was completed and team 4 will continue work on this via issue #164.
