### ISSUE TITLE
Methodize ClientSideGui.java

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#123]
For this issue, we will need to:
a.  Encapsulate the code into methods
b.  Properly JavaDoc those methods
c.  Update Wiki with the Method information once this issue has been completed and/or closed

**Comment by SasquatchMighty** [comment]
Thank you srodriguez4 and thugmunch for your help. Team6 is grateful.

**Comment by TiberiusMagnus** [comment]
We as a team decided to work on other visual items of the Client Side GUI. This may be a worth willed objective in the future; however, team 6 will not be executing this feature.

File Path: ClintSideGui.java
Commit: e8b5cdae211225b5bd95df9d253a82a748d5baca
