### ISSUE TITLE
File Sending Function Broken

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#129]
As of the time of this writing, the client cannot properly create a file given information from the server, or vice versa. A new file is entitled "filename"-copy.txt is created, but nothing is put into the file. I personally think this has something to do with the threading functions, but someone else may know more than I do. Consider this issue fixed when the client can write to the server, ask for a file by name, and put a file exactly like the one in the server into it's own directory.

**Comment by Swilloughby-github** [comment]
File transfer function has been overhauled and now works properly.

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github By which commits?
