### ISSUE TITLE
Transition From Node Traversal to XPath Evaluation

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#130]
Currently, our GUI uses Node Traversal when evaluating XML to get file names and extensions.

This works, but it's relatively messy and I think using XPath will be a better way of getting values from XML.

**Comment by rsanchez-wsu** [comment]
@masters1222 Please make the description of this issue more concrete in terms of what should be completed within the scope.

**Comment by randymusser** [comment]
xml parsing now uses xpath rather than node traversal.
