### ISSUE TITLE
Fix the Header of the File logj42.xml

### ISSUE THREAD

**Issue by SasquatchMighty** [rsanchez-wsu/jfiles#133]
/JFiles/src/edu/wright/cs/jfiles/common/log4j2.xml
The file logj42.xml inside the origin main branch, and subsequently our team6 branch after our last merge, is displaying a warning. “Line does not match expected header line of ‘^V*$’.” (Not the V in the regular expression is inverted in the actual warning message.) However, the header looks to be in the proper format. In an effort to correct this our first step should be to track this back to the team of origin. Perouse their files and see if they have already fixed this issue but have not yet pushed the solution. If they have not solved this issue yet our next step will be to contact them and work with them to solve the issue. We need to handle this with care as this is not our file and any alterations have the potential to negatively impact another team.

**Comment by tytrip** [comment]
@sasquatchmighty @bdenlinger @christofo @darthpacer @michaelmorath this would have come from Team 2. We can look into this and see about getting a fix pushed out. Thank you for bringing this to our attention

**Comment by SasquatchMighty** [comment]
Thank you for your speedy response. If you need a hand shoot me a email.
I was briefly looking into this and saw this mystery problem has occurred
on other GitHub repositories.

Jason Phares (GitHub ID: SasquatchMighty)

**Comment by rsanchez-wsu** [comment]
@SasquatchMighty @tytrip I have #87 assigned to me to handle this.  I haven't been able to get to it yet.

**Comment by w012bwh** [comment]
This issue has been created for Mr. Sanchez.  There isn't a need to keep this one open when he is taking a look at the issue.  This is redundant and will be closed.
