### ISSUE TITLE
T5-M1-I4: Continue Research into Exsisting Classes/Interfaces

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#14]
# T5-M1-I4: Continue Research into Exsisting Classes/Interfaces

> <p>4) Team 5 shall finish researching the functionality of the File built-in class and the Runnable built-in interface to see if and how they will be useful.</p>

<p>For this issue, team 5 shall continue researching the File class and Runnable interface in Java. This research shall influence long-term goals and directions f the File API. Since the File API hinges on how we use the File class in Java, knowledge of this class will be absolutely critical to the formation of this API. Team 5 should, in particular, answer the following questions/solve the following problems:</p>

### File class:

<ul>
 <li>Which methods in the File class should be passed down to JFile as-is?
 <li>Which methods in the File class should be passed down to JFile after modification?
 <li>Which methods in the File class should not be passed down to JFile?
 <li>Are there any methods in the File class that require modification beyond what a wrapper can provide? If so, how shall these issues be addressed?
</ul>

### Runnable interface:

<ul>
 <li>Can the Runnable interface be used as the team needs in the openAs(Application app) method?
 <li>If Runnable does not provide the functionality the team needs, is there a class or interface that does? What class/interface is it? Does it require modification?
</ul>

---

<p>This issue should take a high priority. Even though it requires no actual coding, the knowledge gained through this research is critical to the creating and implementation of the File API. Without this knowledge, team 5 cannot progress. Post any important or relevant information as comments in this issue.</p>

**Comment by srodriguez4** [comment]
**FILE CLASS**
- openAsExe() File Class
  This is in regards to the fact that "openWith(Application app)" inherently assumes the object is a file to be opened by another application, as opposed to being an application itself. This method should run the application on its own if it is an application and throw an error if it is not (of if there is some other error).    
- delete() File Class
  Deletes the file or directory denoted by this abstract pathname.    
- showProperties()   
- createNewFile() File Class
  Atomically creates a new, empty file named by this abstract pathname if and only if a file with the name does not yet exist.    
- zipFolder()
  For further down the road. This would be simple(r) in Linux, but should have functionality in all OSs if we include it.    
- unZipFolder()
  For further down the road. This would be simple(r) in Linux, but should have functionality in all OSs if we include it.    
- getFileType()
  This is necessary for checking whether a file is indeed a file, an executable, a folder, or something else, for use in other methods.   
- getURI() File Class    
- setURL() File Class  
  Recommended to convert an abstact pathnoame into URL by first converting it into a URI via the toURI method, then convert to URL through URI.toURL    
- rename(StringName)  (renameTo()) File Class  
  This will most likely be run in a GUI made by a team working on a GUI API. We could also remove the input parameter and make the method itself throw the user a GUI, but I prefer to keep the focus of each API separated.    
- lastModified()File Class  
  Used to check when it was last modified    
- getProperties()  
  A GUI for this is advisable.    
- move(Locationlocation)  
  "Location" will be some TBD object. May be File. May be JFile.    
- getSize()  
  For use in determining if a drive has enough room when copying. May also be usable in other ways.    
- getPath() File Class  
  Gets path name string    
- exists() File Class  
  Tests whether the file or directory denoted by this abstract pathname exists    
- setReadable()  File Class        
- setReadOnly()  File Class        
- setWriteable()  File Class        
- setExecutable() File Class  
  **RUNNABLE INTERFACE**
- run()  
  Going to be used to create a thread 

**CLONEABLE INTERFACE**
- clone()
