### ISSUE TITLE
Fix Checkstyle Issue

### ISSUE THREAD

**Issue by tytrip** [rsanchez-wsu/jfiles#141]
Team 4 has discovered an issue (#133) in which our Log4j2 configuration file has been failing checkstyle. Please investigate, fix, and push to team2 branch.

### Completion Goals
- [ ] Fix checkstyle issue
- [ ] Push to team 2 branch

**Comment by rsanchez-wsu** [comment]
@tytrip @DarthPacer This is captured in #87, but feel free to take it over.
