### ISSUE TITLE
Relocate classes from gui package

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/jfiles#142]
I just noticed that the team-3 branch has classes in a package called `gui` under the directory `src/gui`.  Please note that the application has a package structure based on the package hierarchy `edu.wright.cs.jfiles.`  Please refactor the classes so that they are located under the directory `src/edu/wright/cs/jfiles` and the corresponding package.

**Comment by randymusser** [comment]
gui class refactored to be inline with standards.
