### ISSUE TITLE
Checksum - Migrate function to a utility class

### ISSUE THREAD

**Issue by joyceje** [rsanchez-wsu/jfiles#144]
Currently Checksum is implemented in both client and sever. But it would be better implemented to remove duplicate code by creating a Utility Class and having both Server and Client reference that class.
@MichaelMorath

**Comment by rsanchez-wsu** [comment]
This issue is being driven by a comment I made on commit 682fde4

**Comment by joyceje** [comment]
Commit ID: b542dbb95f33c9c4cfe60f9b352f130772a8c47e
