### ISSUE TITLE
Create Scrollable Files / Folders Panel

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#148]
The GUI currently only displays files and folder in a static grid panel. After over populating the grid, each icon will get smaller and smaller until they are unidentifiable or can no longer fit in the window. Making the panel scrollable allows the icons to scale better with the window and enables the user to browse the files more comfortably. A more visual representation of this would be how the file explorer in windows keeps each icon the same size and allows the user to scroll up and down through the files when there are too many to fit in the window.

**Comment by matthews92** [comment]
This part of the GUI is now scrollable.
