### ISSUE TITLE
Remove Test XML and Replace With Actual Data From Server / API

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#150]
The XML that is currently implemented in the GUI is simply for testing. 

We need to start creating the methods for requesting the actual XML from the server / API, storing this in a string, parsing it as we do the test XML string, and using that data to display files / folders in the panel.

This will require changing our parsing code depending on the actual element names that we are using. This will require collaboration with the team working on XML.

i.e. replace the below with the actual XML structure from the API / server.

`String testXml = "<?xml version=\"1.0\"?>" + "<items>"
				+ "<item><name>Test</name><ext>.txt</ext><type>file</type></item>"
				+ "<item><name>Test2</name><ext>.png</ext><type>file</type></item>" 
				+ "<item><name>Folder</name><ext></ext><type>folder</type></item>" + "</items>";`

<hr>

The above represents the state of the issue as it was left by Team 3 in Milestone 11. This semester Team 12 will be adopting this issue along with the other issues in their milestone.

This issue would require collaboration with other teams, namely those working on the server and those working on XML. In its current state the server doesn't have any way to send a client the XML structure of the file system. So until it does this issue can't be completed.

Initially this will most likely be accomplished by factoring out the testXml into a function call that will request the directory data from the server. However the server does not have the ability to fulfill a request like this. Therefore, internally the XML request function may still simply return the testXml until this functionality is available.

**Comment by rsanchez-wsu** [comment]
@masters1222 This issue should probably be fleshed out with some details in terms of which methods will change over first, how they will be tested, etc.
