### ISSUE TITLE
Fix Searching (find command)

### ISSUE THREAD

**Issue by JDampCoder** [rsanchez-wsu/jfiles#153]
The "re-code" has broken the find command and cannot find anything when searching. This needs to be fixed as well so that our main purpose is working.

**Comment by kryan100** [comment]
Search should be fixed with my last commit https://github.com/rsanchez-wsu/jfiles/commit/3fae4592cf50aa4b1ebac340cd1f697670e8aa65

**Comment by JDampCoder** [comment]
you should add fixes #153 or something so it will automatically be closed

**Comment by JDampCoder** [comment]
I merged kryan100s code and ran it. It works and the find command is fixed.
