### ISSUE TITLE
Config XStream method

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#159]
To abstract some parts away from the constructor, it is necessary to write a private method the configures XStream.

### Completion Goals ###
Stub out a confXStream method.

**Comment by bdenlinger** [comment]
Need to consider moving this to a static initializer.

**Comment by tytrip** [comment]
Not sure when this was completed, but there is already a static init block that does the configuration work for XStream. Thus, I am closing this issue.
