### ISSUE TITLE
Post Test Plan for File-Sending Functions

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#160]
We need to have a set procedure for testing our program's file transfer functions, both for client-to-server and server-to-client. A test plan needs to be put in place that covers as many conditions and scenarios as possible, such as what should happen when no problem occurs or the requested file is not found. This test plan should include requirements (what the function should be able to do) and test cases (running the program in different conditions each time). This issue can be considered finished when we have a test plan with these components submitted to the wiki and the team can verify that this is a thorough procedure for verifying program functionality.

**Comment by Swilloughby-github** [comment]
I wrote up a test plan concerning this on the wiki.

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github Can you provide a link to the test plan on the wiki?

**Comment by Swilloughby-github** [comment]
https://github.com/rsanchez-wsu/jfiles/wiki/Test-Plan:-File-Transfer

https://github.com/rsanchez-wsu/jfiles/wiki/Checksum-Test

https://github.com/rsanchez-wsu/jfiles/wiki/Thread-Management-Test

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github Thanks!
