### ISSUE TITLE
Post Test Plan for Checksums

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#161]
Similar to file-transfer, we need to test how the program handles checksums, such as if it generates them at all, and how it handles matched or mismatched checksums. Similar to the template for file-transfer testing, we need to work as a team to draft a test plan that includes requirements and test cases. The test plan with both of these parts should be posted to the Github wiki and followed by team members every time a change is made to the program.

**Comment by cunningham124** [comment]
https://github.com/rsanchez-wsu/jfiles/wiki/Checksum-Test
