### ISSUE TITLE
Post Test Plan for Thread Management

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#162]
In recent weeks, our program has implemented threading as a way of handling multiple client connections to the server. Some of this functionality has broken or changed parts of the program that were previously well-established. We need to draft a test plan for thread management and follow it as a team to ensure no other functions in the client or server are broken by threads. We need to write up a test plan (requirements and test cases) and post it to the Github wiki. Team members should of course discuss this in detail and work to make the test plan as detailed and thorough as possible.

**Comment by cunningham124** [comment]
https://github.com/rsanchez-wsu/jfiles/wiki/Thread-Management-Test
