### ISSUE TITLE
getAttribute method

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#167]
The FileStruct class needs a method to return a specific attribute if available.  Method header:
`public String getAttr (String name)`

### Completion Goals ###
A method to return an attribute value given a name

**Comment by bdenlinger** [comment]
@MichaelMorath This is supposed to return the attribute value instead of the name.  It would make more sense to name the method `getValue`.

**Comment by MichaelMorath** [comment]
Just checked and somebody already renamed it. It should be good now.

**Comment by MichaelMorath** [comment]
closing this issue as it is completed.
