### ISSUE TITLE
Translate Output of Server to File / Folder Names and Icons

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#17]
After the basic GUI is constructed the next step will be to take output from the server and translate it to folders / files displayed in the window.

i.e. output from the server: C:\Users\foo\bar and C:\Users\foo\bar.txt 
will display in the GUI window as a folder with the name of bar and a folder icon and a text file with the name of bar.txt and an icon of a text file

**Comment by rsanchez-wsu** [comment]
Keep in mind that this application needs to be platform independent.  With that in mind, it probably makes sense to use URL/URI syntax instead of Windows-specific path specifications.
