### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by SasquatchMighty** [rsanchez-wsu/jfiles#175]
We need to create six icons to represent the buttons created in issue #174. These icons will represent the actions of Copy, Paste, Cut, Delete, Open and Create. These images should have dimensions that are square or nearly square. Once finished the icons should be placed in the file JFiles/src/gui/img in the team6 branch.

**Comment by burks20** [comment]
All requested command icons were created and added to the specified directory of gui/img.  Icons are 32x32 pixels, B&W monocrhome, with transparent background.  Additional command icons were also provided:

•	Copy
•	Cut
•	Delete
•	Download
•	Edit
•	Menu
•	Left arrow
•	Right arrow
•	Open
•	Paste
•	Refresh
•	Save
•	Search
•	Settings
•	Upload
•	Warning

Icons were taken from free vector files under CC 3.0 attribution, with attribution included in the gui/common/FileIconView.css for the time-being.

This concludes issue #175, an extension from issue #174.
