### ISSUE TITLE
Current Directory Area

### ISSUE THREAD

**Issue by SasquatchMighty** [rsanchez-wsu/jfiles#176]
Below the Toos/Widget Area will be the Current Directory Area referenced in issue #174. This area will inform the user where they are in the file structure by displaying the file path to their current working directory. This are should contain a label on the left displaying the text “Current Directory: ”. To the right of this a TextField will be added that extends towards the right edge of the window. Include a prompt text as a space filler that mimics a file path. Ensure this area and its elements are sufficiently distinguishable from the remainder of the window. This could be as simple as coloring the background, or color filling the TextField and the label. These components will be added to an HBox or a GridPane to make them easy to adjust and add to other panes.

**Comment by ianbarney** [comment]
I have completed this Issue, but forgot to reference it in my commit message.

**Comment by rsanchez-wsu** [comment]
@ianbarney Please mention the commit ID in a comment here and then browse to the commit in GitHub and also make a comment on the commit referencing the issue number.  That will ensure that we are able to track when/where/why items are closed.

**Comment by rsanchez-wsu** [comment]
@ianbarney Thanks.
