### ISSUE TITLE
Making Folders and Files Clickable

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#18]
After the files and folders are displayed on the screen, clicking on them should have a corresponding action.

The action created by clicking the button for this issue is generic. It simply puts into code the basic structure of how clicking an button in the GUI works. This will later be altered to multiple types of buttons that have different actions based off of file type.

**Comment by rsanchez-wsu** [comment]
@matthews92 Is this issue really closed by commit 83b77ea?  It does not look like it to me.  Additionally, the idea of single clicking on a file icon triggering a download is not something that seems right to me.  In a file browser a user would typically expect a single click to only select that item.  The download might be a right-click behavior available through the context menu or a double-click behavior.

**Comment by matthews92** [comment]
@rsanchez-wsu What we decided on in class was to first make a functioning set of buttons that just do any simple thing and then what they actually do when clicked would correspond later.  This is why the differentiate types of buttons issue was made (#50 ). I will adjust them now for clarity.

**Comment by rsanchez-wsu** [comment]
@matthews92 Thanks!
