### ISSUE TITLE
Collaborate with team 4 on the LIST command

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#182]
Collaboration work is needed to integrate the XmlHandler work into the LIST command so that it when the LIST command is processed it outputs Xml to the client.

### Completion Goals ###
Send Xml to the client
Additional issues to address needs:
 - [x] #191

**Comment by DarthPacer** [comment]
@bdenlinger is this done?

**Comment by bdenlinger** [comment]
They've not attempted to use it, so we can't close it yet.

**Comment by DarthPacer** [comment]
@ChronoAnomaly Confirmed the changes on SLACK in the team4 channel. I am closing this issue and will proceed with merging into master.
