### ISSUE TITLE
Collaborate with UI teams to parse the deserialized object into their work

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#183]
UI teams also need to be aware of work done and how to use the deserialized object.

### Completion Goals ###
Work with UI teams to get object parsed
Add more issues as needed to address needs,

**Comment by DarthPacer** [comment]
@bdenlinger What is the status on this one ?

**Comment by DarthPacer** [comment]
@ChronoAnomaly Confirmed the changes on SLACK in the team4 channel. I am closing this issue and will proceed with merging into master.
