### ISSUE TITLE
Add Functionality From Team 3 GUI into Team 6 GUI

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#184]
Team 3 and Team 6 have merged branches to the team-3-6-dev branch.

The team 3 GUI currently translates a string of XML to clickable files / folders on the screen while Team 6's GUI handles the login, and the general design of the window.

The XML parsing and file / folder displaying need to be implemented into Team 6's GUI. Assuming that Team 6 has a jpanel where files / folders are to be displayed, this should be as simple as using Team 3's current code but changing which panel the files / folders are displayed in.

After merging the two branches into a team 3-6 dev branch the two GUIs are still in separate classes. These two designs should be integrated to each other so that both teams can work on the same GUI. This will likely result in code creating the output text region, URL path display, and file population being moved into Team 6's frame along with the code they have written. It is ideal that the code written by our team retains its separate method calls when being transferred.

**Comment by matthews92** [comment]
Updated issue description to add in the very similar issue #179 and closed #179 to avoid confusion.

**Comment by mdgilene** [comment]
This appears to have been completed. ClientSideGui.java does parse XML in order to populate the view with files.
