### ISSUE TITLE
Create a New Branch off of Team1-Dev for Remote Objects

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#185]
To maintain the integrity of our current work on the project, it would be best if we created a separate branch off of team1-dev (titled something like team1-dev-rmi) and began work on remote object implementation. The closing conditions for this issue are simple: When we have a branch for remote objects (branching from team1-dev) on Github, we can consider this issue finished.

**Comment by slyr91** [comment]
Remember that the -dev needs to be last

**Comment by Swilloughby-github** [comment]
A branch has been created.
