### ISSUE TITLE
Identify what features and options our client side GUI should possess. 

### ISSUE THREAD

**Issue by SasquatchMighty** [rsanchez-wsu/jfiles#19]
This will be a whole team effort.
btdugas and cspencer44 are also assigned to this issue, but as of yet they are not on the list of possible assignees.

**Comment by rsanchez-wsu** [comment]
@SasquatchMighty Could you flesh out this issue with a more detailed description and clear objectives as to what it is meant to accomplish?  As it is, the description is very vague.

**Comment by SasquatchMighty** [comment]
Team 3 and Team 6 are collaborating on the projects GUI designs. On our joint slack page named “gui_collaboration” (https://ceg3120fall2016.slack.com/messages/gui_collaboration/) there is a simple list of GUI features drawn from both teams’ wiki pages. The list is currently divided into priority features and secondary features. Priority features are things we believe need to be implemented if our GUIs are to be respectable. The secondary list is a list of features that will polish the GUIs but are not crucial to the projects operation. 
A special thanks to team 3s nickwvr (SlackID) for his initiative.

**Comment by rsanchez-wsu** [comment]
@SasquatchMighty Nice. Thank you.
