### ISSUE TITLE
Search Area

### ISSUE THREAD

**Issue by SasquatchMighty** [rsanchez-wsu/jfiles#192]
Below the Current Directory Area referenced in issue #176 will be a Search Area. This Search Area will consist of a button and a text field. The idea being that a user types a key word into the text field then presses the button to launch a search of the file structure. The button should contain the Prompt Messages “Search”. When pressed it should collect the text field input and store it into a variable. The text field should be fairly large, at least 25 characters long. The final size is up to the coder as the text field may need to be adjusted to fit the window. The button and text field should be added to an HBox or GridPane to ensure they are on the same level side by side and facilitate later relocation ease.

**Comment by ianbarney** [comment]
Switching over to CSS we need to redo this issue, but it shouldn't be too hard. I think when you click search we should have a method that sets currentDirectory to what's in the search bar and passes it to the loadDirectory method.

**Comment by elliottfries** [comment]
A search area has been implemented.
