### ISSUE TITLE
Run a successful ant clean test on our branch

### ISSUE THREAD

**Issue by matthews92** [rsanchez-wsu/jfiles#195]
To my knowledge, our code has not been run through ant yet. We are not supposed to merge to master until an 'ant clean test' is run. This should be done to prepare the next class to take over our code without being hindered right off the start. This also allows us to push the branch to master and allow other teams to use the code more safely. This issue will be complete when an indication by Travis shows that an ant clean test was successful for our code.

**Comment by mdgilene** [comment]
Resolved with issue #234
