### ISSUE TITLE
T1-M9

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#196]
As the semester is coming close to a wrap-up, we need to adjust our branch of the program so that it's quality and style are consistent with the work of the other teams. As our code has gone through many changes, there are a great deal of obsolete aspects that need to be changed or deleted. The work for this week's milestone can be summarized in the following list:

1. The instructor adjusted the CheckStyle settings on the master branch. We need to merge master into our branch and address any additional complaints it may bring up.

2. Add filename-copy files to .gitignore. Commit this change.

3. Remove obsolete functions (one example can be found in an issue to be posted).

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github What was the reason behind closing this issue?  Is there a commit that took care of items 2 and 3 on your list?  Did master also get merged in at some point?
