### ISSUE TITLE
Add filename-copy Files to .gitignore

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#199]
Originally, our program created a new file named in the format "filename-copy.txt" when transferring files. This function is obsolete in our programs current state. We need to make a commit with the test file and the copy of that file added to .gitignore so that they do not show up every time someone pulls a commit from GitHub. Consider this issue closed when the demo.txt and demo-copy.txt files are a part of .gitignore and are not added to the repository when a commit is pulled from the team's branch.

**Comment by rsanchez-wsu** [comment]
It is also possible to use wildcards or file globs in .gitignore.

**Comment by burks20** [comment]
All files containing the postfix "-copy" no longer exist in our project directory, but a filter was added to .gitignore in case it's ever needed.  

Commit is https://github.com/rsanchez-wsu/jfiles/commit/4a82c05ae036eedeeca1117a339476bd14ae40f2

This issue well be closed.
