### ISSUE TITLE
Create a possible pictorial representation of the planned client side GUI.

### ISSUE THREAD

**Issue by SasquatchMighty** [rsanchez-wsu/jfiles#20]

**Comment by rsanchez-wsu** [comment]
@SasquatchMighty Could you flesh out this issue with a more detailed description and clear objectives as to what it is meant to accomplish? Aside from the title there is not even a description.

**Comment by SasquatchMighty** [comment]
In closing Issues #19 and #61 we also resolved this issue.
When Team 3 and Team 6 collaborated on the projects GUI designs a collective GUI Mockup was created. It can be found on our joint slack page named “gui_collaboration” (https://ceg3120fall2016.slack.com/messages/gui_collaboration/) as well as below. 
The mockup currently shows the following features: 
•    refresh button
•    back and forward button
•    different icons for different file types
•    scrolling
•    file path display
•    search for files, connectivity display
A special thanks to team 3s nickwvr (SlackID) for his initiative.

**Comment by rsanchez-wsu** [comment]
@SasquatchMighty Would you mind posting the mockup here, for the benefit of future students who might not have access to the current Slack team?

**Comment by SasquatchMighty** [comment]
![erik_early_gui_mock_up](https://cloud.githubusercontent.com/assets/14119599/19616120/5e6b7e18-97d9-11e6-8ef0-186ed8e39328.jpg)
Sorrry, I refrenced the image in the above comment but forgot to include the image.

**Comment by rsanchez-wsu** [comment]
@SasquatchMighty I seem to recall having seen that image elsewhere, but I am glad it's here now.
