### ISSUE TITLE
Remove fileSystem.dtd from common package

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#202]
As it is no longer needed, we need to remove the dtd from the common package.

**Comment by DarthPacer** [comment]
@rsanchez-wsu The issue called to the delete the .dtd file, I was unsure whether or not we wanted to preserve the work we did before changing approaches so instead, i created a new package called "RetiredClasses", and stored the .dtd file in there. Is this the wrong approach? should I just delete the file ?

**Comment by rsanchez-wsu** [comment]
@DarthPacer I would rather just have it be deleted.  The issues and commit history describe what has happened (assuming decent summaries and descriptions).  We can always reconstruct/restore it from history later if needed.
