### ISSUE TITLE
Discuss How Test Code Should Work

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#205]
Need to read over the descriptions for what each method in the API testing class does and determine whether all of the descriptions are up-to-date for the class. If not, we need to discuss any changes that must be made either to the code or the description. It is okay if the code does not match the description exactly, so long as the description adequately described where we want the code.

**Comment by lroberts108** [comment]
Newer issue #277 is an expansion of what this issue began to discuss. I am going to close this issue so we do not have multiple discussions happening about testing the project as a whole. Other issues have been created for specific testing implementations such as #279 and #260 

In short, we have decided to use and implement the jUnit test suite.
