### ISSUE TITLE
Prepare and push 'Team 2' branch to Master

### ISSUE THREAD

**Issue by DarthPacer** [rsanchez-wsu/jfiles#206]
I am completed with this issue, once the following have been resolved:
- [x] All Check-Style issues have been fixed
- [x] All Find Bugs issues have been fixed
- [x] Code has been well commented and documented
- [x] Ant completes a clean build of the 'Team 2' branch
- [x] 'Team 2' branch has been pushed to Master

**Comment by DarthPacer** [comment]
Everything is working and ready to be merged. When i attempted to merge, I was getting conflicts and was unsure how to resolve them; as I have not merged before. I opted to not merge, and reverted back to how it was.  Nothing was affected by me doing this and Is ready for someone else to merge it into master. All bugs and checkstyle issues have been resolved.

**Comment by mdgilene** [comment]
Fixed with 53570e3277dffbd955f8011d2e288c5d3007274f
