### ISSUE TITLE
Summarize final thoughts on team 6 wiki page

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#211]
On Thursday, 12/1, we as a team discussed how we would use the last week of classes on the project.  One suggestion was to write up some final thoughts in the team's wiki page.
This will be an effort for all team members to compile their final thoughts in the wiki page for team 6.

**Comment by SolidStateHero** [comment]
Invalid and closed - We do not have the team currently working on the project to give final thoughts.
