### ISSUE TITLE
Remove old milestones and link old issues to newer relevant issues

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#212]
With the last milestone taking effect in the last week of classes, it is important that we close all old milestones. However, we will not close the issues contained in them but rather reference in comments to newer issues.

**Comment by hbarri** [comment]
Can this issue be closed since all of the old milestones have already been cleaned up?

**Comment by SolidStateHero** [comment]
I would argue yes. I've been through all of the issues and milestones, and anything that is left could contain important information. Closing this now.
