### ISSUE TITLE
Resolve all warnings before master merge

### ISSUE THREAD

**Issue by kryan100** [rsanchez-wsu/jfiles#213]
Before we can push to master, we need to resolve all warnings. Currently these include:  

- [x] Deprecated stop() method in JFilesServer, JFilesServerThread, and JFilesClient
- [x] Deprecated readLine() method in JFilesClient
- [x] Unused variable "server" in JFilesServer (We can probably suppress this one)
- [x] Unused variable "client" in JFilesClient (Probably suppress this one too)

**Comment by markbrant621** [comment]
I reviewed the errors in this issue, but I will need further testing on the Deprecated stop() methods before I am able to push it to master.

**Comment by markbrant621** [comment]
All @depricated and @ unused warnings are currently fixed. the server ones were fixed by the team working on the server issues, the unused ones seem to be fixed beforehand, I fixed the client one. i am closing this issue since they are all fixed.
