### ISSUE TITLE
Make Final Comments in Code

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#215]
Write comments all throughout our code that explains all functions and why they are implemented. As usual for documentation-based issues, the close conditions for this are ambiguous and rely on our judgement of how well our code is explained in the comments.

**Comment by jasonmarcum** [comment]
Andrew Ribar and I have completed this issue, but we are still having trouble committing the changes. Once we can figure that out we will be able to close this issue.

**Comment by ElderReebs** [comment]
This commit essentially finishes up issue #215 from Milestone 1 and when it carried over to Milestone 2, and some work on issue #216 in the JFilesClient class from Milestone 2.  Issue #216 has just been started so we have more work to accomplish before we can wrap this issue up. Here is the link 22169e1 commit.
