### ISSUE TITLE
Document Methods/Classes

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#216]
Review, understand, edit, and add on to the comments previously written by team1 to clearly understand the code written and its uses. Descriptions should include method names, parameters, packages, return types, and a brief overview of what each method does. Class descriptions should have an overview, package, and listings of all constructors. We should document this information using either wiki, JavaDoc, or text files, whichever we find works best. This issue will be closed when all classes and methods in our repository are documented and all code-related documentation ends up in JavaDoc comments, which will be generated and published here on the GitHub project (issue #248).

**Comment by rsanchez-wsu** [comment]
Let's make sure to keep in mind the eventual goal is for all code-related documentation to end up in JavaDoc comments, which will be generated and published here on the GitHub project (#248).

**Comment by w262jxl** [comment]
There are already javadoc comments associated with each method/class. What else needs to be done for this issue?

**Comment by w262jxl** [comment]
Methods and classes have been documented into the wiki pages. Team 1 Branch Documentation.

**Comment by rsanchez-wsu** [comment]
@w262jxl Could you provide full links to the wiki pages where these are documented?
