### ISSUE TITLE
Cleanup our Issues

### ISSUE THREAD

**Issue by DarthPacer** [rsanchez-wsu/jfiles#219]
Go back through all open/closed issues and ensure all issues that are completed by us, are documented with the proper wiki page to look at to know more information; and any commit ID's associated with them. Additionally, we need to ensure all open Issues are valid, and none are no longer needed/already completed.

**Comment by SolidStateHero** [comment]
I am closing this issue with approval from @rsanchez-wsu as most of the other open issues will be closed as code progresses.
