### ISSUE TITLE
Insert a 'Reflection' Entry into Team 2 Wiki

### ISSUE THREAD

**Issue by DarthPacer** [rsanchez-wsu/jfiles#220]
I know I am done, when a page exists on the Team 2 Wiki, that has a short reflection on the semester. The reflection can include what we learned, what we did, and what we would like to become of the project.

**Comment by DarthPacer** [comment]
I know I am done, when a page exists on the Team 2 Wiki, that has a short reflection on the semester. The reflection can include what we learned, what we did, and what we would like to become of the project.

**Comment by DarthPacer** [comment]
I have created the page, and put under 'Team 2' -> 'Thoughts and Ideas for future'. Everyone has the opportunity to write up a reflection about this semester as it regards to the project and this class. I created an opening paragraph, but this will probably be modified before the end of week; as the wording is still not right. Additionally, I am open to suggestions for renaming the sub portion of the Team 2 Wiki, as right now, it is a little long winded.

**Comment by DarthPacer** [comment]
Renamed the sub-portion of the wiki and reorganized the page layouts. Additionally, updated my reflection and encourage the rest of the team to do-so aswell.

Commits:
3d38c93
b766887

**Comment by MichaelMorath** [comment]
I've added my entry to the reflection page.

**Comment by DarthPacer** [comment]
Seems everyone did on who wanted too, so I am closing this issue as no more work is going to be done on the project; and this can't really be continued by another group of students.
