### ISSUE TITLE
T5-M10-I4: Create a Team 5 Goals and Objectives Wiki Page

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#222]
I had initially started a page detailing the goals and objectives of Team 5, and even got quite far, but then mistakenly closed the page losing my work. This page would be greatly useful to more accurately describe what the goals of the team is. Where the File API Wiki is about the objectives of the code, this wiki will be more about the team overall. This is what we want to accomplish in a more broad sense, while a wiki page on what ideas we have to continue the project will be about specific ideas that the nest team may or may not be interested in.

**Comment by SolidStateHero** [comment]
This issue was never closed, and we do not have the previous team to give us the goals and objectives.
