### ISSUE TITLE
NEEDS MOVED TO THE WIKI: How to: Import and Implement The Bootstrap CSS Library with the GUI

### ISSUE THREAD

**Issue by ghost** [rsanchez-wsu/jfiles#226]
Bootstrap is one of the worlds most popular styling libraries for the web. To enhance the visuals in the GUI we can let this library style it with a more modern style.

Download the bootstrap library at: http://getbootstrap.com/getting-started/#download. I recommend downloading the minified version to have a reduced size copy. 

Import the library into your project. 

To implement bootstrap in JavaFX you will have to use WebViews because bootstrap must directly work with html. You can read about WebViews here: http://docs.oracle.com/javafx/2/api/javafx/scene/web/WebView.html. WebViews allows us to use HTML rendering with css and javascript. 

To implement and see an example try looking here: http://stackoverflow.com/questions/21268062/bootstrap-with-javafx

**Comment by mdgilene** [comment]
One thing to consider (assuming I'm understanding correctly) is tht at the current GUI would require significant rework in order to use Web Views instead of the regular javafx views (panels, buttons, labels, etc.)

**Comment by rsanchez-wsu** [comment]
@willeko999x I believe that the purpose of this issue was just to clearly document the content that was in the initial write up.  Is your intent in adopting this issue to do only that, or do you intend to start work on a Bootstrap effort?

**Comment by SolidStateHero** [comment]
The plan was currently just to complete the issue as a part of our clean-up effort by moving it to the wiki. 

Edit: However I wouldn't be opposed to integrating Bootstrap in a future milestone.

**Comment by SolidStateHero** [comment]
I have moved the content of the issue to the wiki with a few changes and organizational additions, thus closing the issue. It is located at [https://github.com/rsanchez-wsu/jfiles/wiki/Optional:-Implementing-Bootstrap](url). If there are any future suggestions or edits, feel free to make them.

**Comment by rsanchez-wsu** [comment]
@willeko999x Thanks for clarifying and thanks for posting a link to the new wiki content.
