### ISSUE TITLE
Refining Table Of Contents 

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#228]
I feel that the table of contents for the wiki should be refined. The primary issue I have with the wiki's table of contents is that it cannot be carried over from one semester to the next. If last semester's team 2 worked on the core package and this semester's team 8 works on the core package, the title will have to be changed to `team 2 and team 8`, and so on. It seems to be that it would be a better idea to name the table of contents after the packages, rather than the teams.

If anyone has feedback about this idea, I would love to hear it!

My proposed table of contents:

1. Home
1. Development Environment
    1. Ant
    1. Ivy
    1. Eclipse and Eclipse Plugins
1. Packages
    1. core
        1. Argument
        1. Arguments
        1. List
    1. gui
        1. Gui
        1. Item
        1. Parser
    1. client
        1. ClientSideGui
        1. JFilesClient
        1. JFilesClientThread
        1. JFilesGui
    1. server
        1. JFilesServer
        1. JFilesServerThread
    1. gui.img
    1. common
1. Dependencies

**Comment by rsanchez-wsu** [comment]
This looks excellent.  If there are no other suggestions from other folks, I am OK with you reorganizing the wiki in this way.

**Comment by LoganRickert** [comment]
I've gone ahead and:

* Added the proposed sidebar edit to the sidebar (kept the teams at the bottom).
* Added a `pages` section to each team page at the top with that team's table of contents
* Removed each team's table of contents from sidebar.

I think if there are no objects with this edit, it should be okay to close this issue.

**Comment by rsanchez-wsu** [comment]
I like how it looks.  I am OK with closing the issue.  Very nice job.
