### ISSUE TITLE
Formalizing Server Commands

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#231]
Hey everyone,

I just wanted to open a discussion about creating a formal design for commands. Currently, it appears as though server commands were just added at will. This appears to have caused some complications as multiple branches not only have different implementations of commands, but different commands all together with no consistency.

Some Examples:

* [master](https://github.com/rsanchez-wsu/jfiles/blob/master/src/edu/wright/cs/jfiles/server/JFilesServer.java) - LIST, FIND, FINDR, EXIT
* [team1-dev](https://github.com/rsanchez-wsu/jfiles/blob/team1-dev/src/edu/wright/cs/jfiles/server/JFilesServer.java) - SENDFILE, GETFILE, REC_FILE, EXIT, QUIT

## Proposal 1

I propose that there are two categories of messages:

* `Information`
* `Command`

Each message code should be exactly four characters that fit the following filter: `[A-Z]`.

### Argument Format

Arguments are space-seperated tokens that come directly after the message handler.

```
CMD <arg1> <arg2> <arg3> [arg4]

CMD test abc "123 456"

<arg1> -> test
<arg2> -> abc
<arg3> -> 123 456
[arg4] -> {Optional, nothing given}
```

```
CMD <arg1> <arg2...>

CMD test abc 123

<arg1>    -> test
<arg2...> -> abc 123
```

If a message sends too many arguments, the extra arguments should be thrown away during parsing.

### Information

These messages relate information to the other side of the connection.

#### INFO

Format:

`INFO <message...>`

Example:

`INFO Last logged in 10 minutes ago`

#### ERRO

Format:

`ERRO <message...>`

Example:

`ERRO File not found.`

### Commands

These messages tell the client or server to do something.

#### LIST

Lists the contents of a directory.

Format:

`LIST [directory]`

Example:

`LIST src`

Returns:

A new-line delimited list of files in the `[directory]`. If no `[directory]` is given, the current working directory is used.

#### FIND

Searches for a file.

Format:

`FIND <filename> [directory]`

Example:

`FIND *.xml`

Returns:

A new-line delimited list of files that match `<filename>` in `[directory]`. If no `[directory]` is given, the current working directory is used.

#### FNDR

Recursively searches for a file.

Format:

`FNDR <filename> [directory]`

Example:

`FNDR *.xml`

Returns:

A new-line delimited list of files that match `<filename>` in `[directory]` and all sub-directories. If no `[directory]` is given, the current working directory is used.

#### RENM

Renames a file.

Format:

`RENM <from> <to>`

Example:

`RENME build.xml builds.xml`

#### RMFL

Removes files.

Format:

`RMFL <filename>`

Example:

`RMFL *.xml`

Returns:

A new-line delimited list of files that match `<filename>` and were removed.

#### QUIT

Closes the connection.

Format:

`QUIT`

#### RECV

Prepares to receive a file.

Format:

`RECV <filename> <contents...> EOF`

Example:

`RECV test.txt This is the contents of our test file! EOF`

#### SEND

Requests the server sends a file

Format:

`SEND <filename>`

Example:

`SEND build.xml`

Returns:

`RECV` to sender of `SEND`.

#### MKDR

Makes a directory inside of `[directory]`. If no `[directory]` is given, the current working directory is used.

Format

`MKDR <directoryName> [directory]`

Example:

`MKDR testFolder`

#### SCWD

Sets the current working directory to `<directoryName>`.

Format:

`SCWD <directoryName>`

Example:

`SCWD src`

#### USER

Sends the username for the client.

Format:

`USER <name>`

Example:

`USER bob`

#### PASS

Sends the password for the given `USER`.

Format:

`PASS <password>`

Example:

`PASS mypass`

#### RMDR

Removes a directory.

Format:

`RMDR <directoryName>`

Example:

`RMDR testFolder`

## Closing

Any feedback is greatly appreciated!

**Comment by mdgilene** [comment]
Is there any current implementation limitation that is limiting us to on 4 characters for the command? If all commands sent to the server are space-separated then it should be easy to pick out the command as the first token in the string.

Another thought is that it might be useful to reuse the names of commands from a typical Linux shell for our shell. For example, instead of SCWD, this performs the same function as CD. Why not just use CD? This would help with ease of use because people are already familiar with these commands and wouldn't have to learn an entirely new system.

Secondly, instead of having tons of commands that each do something different, we again could follow the Linux shell approach and use flags to modify the behavior of the commands. Example could be instead of having FIND and FNDR, just have a single command FIND with a flag of -R to search recursively. I'm not currently sure how the command system is implemented so I don't know if it would be able to support flags at the moment. If not we would have to do some work to allow flags.

**Comment by LoganRickert** [comment]
The reason I went with a four character set is because FTP commands are generally all four characters long. You are correct that they could be any length without issue.

I like your idea for following Bash shell syntax. I think that if we discard the idea of having commands be four characters long and instead fit with the Bash shell syntax convention, it will indeed be easier to understand and learn.

Flags may be a more tricky thing to implement. The current system is just splitting the string into an array of space-delimited values. Flags have many different syntax types, for example: `cmd -r`, `cmd -name hello`, `cmd -la` (where `l` and `a` are two different flags), `cmd -l -a`, `cmd --extra`. A flag parsing system would have to be implemented. I personally do not think such a system would be too complex to implement but it would definitely take a little planning and work.

An alternative flag parsing system could be a simple flag system, where you do `cmd true false <arg>` where true is a flag and it's being set to true, etc. and is always present.

**Comment by mdgilene** [comment]
Our flags certainly do not need to be as complex as they are with some bash commands. We could simplify it. For example our flags could follow the following format.

`cmd -flag:[param]`

Parameters would be optional.

**Comment by LoganRickert** [comment]
That's actually a really great idea for a good way of handling flags. It would also be a lot more simple to implement.

**Comment by LoganRickert** [comment]
## Proposal 2

I propose that there are two categories of messages:

* `Information`
* `Command`

Each message code should be of any length but fit the following filter: `[A-Z]`.

### Argument Format

Arguments are space-seperated tokens that come directly after the message handler.

```
CMD <arg1> <arg2> <arg3> [arg4]

CMD test abc "123 456"

<arg1> -> test
<arg2> -> abc
<arg3> -> 123 456
[arg4] -> {Optional, nothing given}
```

```
CMD <arg1> <arg2...>

CMD test abc 123

<arg1>    -> test
<arg2...> -> abc 123
```

### Flag Format

Flags are given as so:

Flags:

* `myFlagName1`
* `myFlagName2:<argument>`

Flags are passed in as so:

```
CMD <arg1> <arg2> <arg3> [arg4]

CMD -myFlagName1 -myFlagName2:test abc 123

<arg1> -> abc
<arg2> -> 123
```

### Information

If a message sends too many arguments, the extra arguments should be thrown away during parsing.

#### INFO

Format:

`INFO <message...>`

Example:

`INFO Last logged in 10 minutes ago`

#### ERROR

Format:

`ERROR <message...>`

Example:

`ERROR File not found.`

### Commands

These messages tell the client or server to do something.

#### LS

Lists the contents of a directory.

Format:

`LS [directory]`

Example:

`LS src`

Returns:

A new-line delimited list of files in the `[directory]`. If no `[directory]` is given, the current working directory is used.

#### FIND

Searches for a file.

Format:

`FIND <filename> [directory]`

Flags:

* `R` - recursively search through `[directory]`s.

Example:

`FIND *.xml`

Returns:

A new-line delimited list of files that match `<filename>` in `[directory]`. If no `[directory]` is given, the current working directory is used.

#### MV

Moves or renames a file.

Format:

`MV <from> <to>`

Example:

`MV build.xml builds.xml`

#### RM

Removes a file.

Format:

`RM <filename>`

Flags:

* `R` - recursively search through `[directory]`s for files to delete.

Example:

`RM *.xml`

Returns:

A new-line delimited list of files that match `<filename>` and were removed.

#### RMDIR

Removes a directory.

Format:

`RMDIR <directory>`

Example:

`RMDIR testfolder`

#### TOUCH

Creates an empty file.

Format:

`TOUCH <filename>`

Example:

`TOUCH test.txt`

#### MKDIR

Creates a directory

Format:

`MKDIR <directory>`

Example:

`MKDIR testfolder`

#### QUIT

Closes the connection.

Format:

`QUIT`

#### RECV

Prepares to receive a file.

Format:

`RECV <filename> <contents...> EOF`

Example:

`RECV test.txt This is the contents of our test file! EOF`

#### SEND

Requests the server sends a file

Format:

`SEND <filename>`

Example:

`SEND build.xml`

Returns:

`RECV` to sender of `SEND`.

#### CD

Sets the current working directory to `<directoryName>`.

Format:

`CD <directoryName>`

Example:

`CD src`

#### PWD

Gets the current working directory

Format:

`PWD`

Returns:

The full directory path of the current working directory. 

#### LOGIN

Logs into a user account.

Format:

`LOGIN <username> [password]`

Example:

`LOGIN bob`

**Comment by rsanchez-wsu** [comment]
@LoganRickert This issue is on your team's milestone, but there is no statement regarding the deliverable or desired end state.  Please make sure that something gets added here at some point so that it is properly documented.

**Comment by LoganRickert** [comment]
The deliverables for this issue are:

- [x]  Agree on a standard representation for flags
- [x]  Agree on a standard representation for arguments
- [ ]  Agree on an initial set of commands and for each command: what is the command, the arguments, the flags, and how will it be helpful for the server to have.

**Comment by cklw5858** [comment]
I agree with Proposal 2 to follow more of a Linux shell approach. I like @mdgilene idea for flags:
cmd -flag:[param]

Parameters would be optional.

**Comment by LoganRickert** [comment]
I think at this point the structure is pretty concrete. I am closing the issue.
