### ISSUE TITLE
Clean Up Team 4's Branches

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#232]
All of Team 4's branches need to either be retired or merged in master.

- [x] Merge team4-alt-dev
- [x] Merge team4

- [x] Merge team4-dev

**Comment by Rotbot9k** [comment]
please retire team4 and team4-dev'. I'm not sure how you retire a branch. Isn't there a way to make it 'inactive' without deleting?

**Comment by LoganRickert** [comment]
Is it something like this? http://stackoverflow.com/a/1309934

**Comment by rsanchez-wsu** [comment]
@LoganRickert I like the approach suggested in the SO posting

**Comment by LoganRickert** [comment]
* team4-alt-dev has been merged through team4-tomerge branch and both branches deleted.
* team4-dev has been deleted.
* team4-team4 has been deleted.
