### ISSUE TITLE
Assess removal of team3 branch

### ISSUE THREAD

**Issue by mdgilene** [rsanchez-wsu/jfiles#233]
I think we are ok to remove the team3 branch. I've taken a look through the code and it doesn't appear to have been touched since early on in the project. The GUI is basically a place holder and doesn't contain any meaningful features. The client/server do work but are very simple and missing features/code that are present on master and other teams branches.

I propose the branch be ditched entirely. If anyone else has a different opinion on how this should be handled feel free to post below.

**Comment by LoganRickert** [comment]
I just had a look and I couldn't agree more. 

What I did for the other branch was tag as archive, push the tag then deleted the branch locally and remotely.

**Comment by mdgilene** [comment]
This method?

http://stackoverflow.com/questions/1307114/how-can-i-archive-git-branches
