### ISSUE TITLE
Merge branches team3-dev and team-3-6-dev

### ISSUE THREAD

**Issue by mdgilene** [rsanchez-wsu/jfiles#234]
At some point in the previous semester teams 3 and 6 started working together on a joint branch. We need to assess the state of the two branches and determine how to merge the two.

**Comment by mdgilene** [comment]
From what I can tell team-3-6-dev is also obsolete.

It was merged to master with commit 341a7e6d96d189d5943b5d38c0220547dc2472ab. Since this merge there is only 1 more commit on this branch 46a3f468cef70218096eb8310566c0d95b8dcfe2. This commit is trivial to merge into master at this point.

At this point I propose merging the existing team-3-6-dev branch to master and then archiving that branch.

This also means that since team-3-6-dev is ahead of team-3-dev, I believe we are safe to archive team-3-dev as well

**Comment by LoganRickert** [comment]
Was team3-dev merged to master yet? I thought you committed to team3-dev earlier.

**Comment by mdgilene** [comment]
Oh yeah, then I guess merge those changes into team-3-6-dev then to master. That should take care of both branches then both can be removed.

**Comment by mdgilene** [comment]
team3-dev has been merged into team-3-6-dev.
team-3-6-dev has been merged into master
