### ISSUE TITLE
Create Team 11 Wiki Page

### ISSUE THREAD

**Issue by SolidStateHero** [rsanchez-wsu/jfiles#238]
**The following issue can be closed once the following criteria are met and cleared:**

- [x] Create and develop wiki page for Team 11
- [x] Create format guidelines for additions to the wiki page, which should include:
   - [x] Team member names
   - [x] Development practices
   - [x] Merge policies
   - [x] Current Milestone summary
   - [x] Completed issues with documentation

There is currently no wiki page for Team 11. While creating it, we should consider a few things:

1. Other team's page formats.
2. What format would be best for continued addition.

We also need to make a format standard for our page, so future and current contributors can easily understand what we have achieved and documented.  This would be located in the same Team 11 wiki page, not as its own page, to avoid bloat. The format guidelines should include the above criteria, and be in a format that can be copied for future additions.

**Comment by rsanchez-wsu** [comment]
To be complete, this issue's summary should list the specific items that will be on the wiki page in order to consider it complete.  For example, team members, team-specific development practices, merge policy, etc.

**Comment by rsanchez-wsu** [comment]
@willeko999x @kcopper Can you please provide a link to the wiki page?

**Comment by SolidStateHero** [comment]
Closed, page located at: https://github.com/rsanchez-wsu/jfiles/wiki/Team-11
