### ISSUE TITLE
Analyze and Redocument Current GUI Code where Necessary

### ISSUE THREAD

**Issue by SolidStateHero** [rsanchez-wsu/jfiles#239]
The following issue will be closed when these criteria are met:

- [x] Current GUI code has been thoroughly searched for any incorrect or inaccurate documentation.
- [x] Current GUI code is properly recorded in javadoc, class-level, and method-level documentation.

Keep in mind that this may involve simply going through the code and changing nothing at worst. If this is the case, it would still be a good idea to research the code for our team to get a better grasp of what the code in the GUI section is working towards, as well as a head start for future milestones.

**Comment by rsanchez-wsu** [comment]
Some things to consider here are: 1) you don't define what format issues are being targeted or how they are to be addressed; 2) you don't define what "properly documented" means; and, 3) as an FYI, there were some efforts to document code in the wiki, but I don't like that as I would rather see more documentation, especially class-level and method-level documentation, in Javadoc and leave the wiki for process-oriented and perhaps architectural documentation.

**Comment by rsanchez-wsu** [comment]
Let's make sure to keep in mind the eventual goal is for all code-related documentation to end up in JavaDoc comments, which will be generated and published here on the GitHub project (#248).

**Comment by SolidStateHero** [comment]
This issue may be done/completed already. I only found a few comments that need subjective minor changes. I would like the rest of my group or anyone else who wants to help to look for me. The documentation is very well done and the code is fairly simple in composition. If there are no other problems I will push what little I've done and close this issue.

**Comment by SolidStateHero** [comment]
I've made another look through and I believe that the current code is documented properly.
