### ISSUE TITLE
Reevaluate Project Architecture

### ISSUE THREAD

**Issue by mdgilene** [rsanchez-wsu/jfiles#240]
The purpose of this issue is to discuss the current project architecture. At the moment the architecture has grown naturally over the course of the previous semester by multiple teams. As it stands now it is sufficent for the current state of the project however I could see issues arising later on as the project gets larger and more complex. Because of this I think we should formalize the architecture of the project now while it is still relatively simple.

I have created a wiki page [Project Architecture](https://github.com/rsanchez-wsu/jfiles/wiki/Project-Architecture) that contains the layout of the project in its current state and a possible structure we can move towards. 

This is a pretty large change to the code base that would require the movement of files and renaming of packages. Because of this all teams will need to be involved in this process. However before anything is actually done we need to decide on the final structure and then document it in the wiki page.

We will use this issue as the discussion area for this topic.

**Comment by rsanchez-wsu** [comment]
@mdgilene Fantastic work with this.  I like the new structure.
