### ISSUE TITLE
Consolidate GUI code into a single package and remove secondary GUI

### ISSUE THREAD

**Issue by mdgilene** [rsanchez-wsu/jfiles#241]
Currently there are three GUIs that were being worked on at the end of last semester. Because of this we need to consolidate their code into a single package and remove one of the duplicate GUIs.

The more fleshed out GUI is ClientSideGui located in the client package. Because of this, we will be moving forward with this design as the base for the rest of this semester.

The follow lists what actually needs to be done in order to close this issue

- [x] Verify that all major features of GUI.java are present in ClientSideGui.java.
- [x] Remove GUI.java and JFilesGui.java.
- [x] Move ClientSideGui.java into the GUI package.
- [x] Resolve any import conflicts that may arise.

**Comment by LoganRickert** [comment]
I've been wondering myself why there are two GUIs. Does anyone actually know? I've just been assuming the GUI package is the official GUI.

**Comment by mdgilene** [comment]
I believe there were two teams working on the GUI last semester. It appears as thought they started developing it separately but then started working together near the end of the semester and began to merge their two designs together. So currently ClientSideGui can do everything GUI can do plus some extra things.

**Comment by rsanchez-wsu** [comment]
@mdgilene You are correct.

**Comment by mdgilene** [comment]
Didn't even realize, but turns out there are actually 3. However, JfilesGui in the client package is completely obsolete so it will be removed as well.
