### ISSUE TITLE
Create Team 7 Documentation on Wiki

### ISSUE THREAD

**Issue by cklw5858** [rsanchez-wsu/jfiles#242]
Create a Team 7 Wiki page that will be used for our team's documentation. This is where we can put our goals, milestone information, release notes, etc. This will be beneficial in order to compile help documentation at the end of the semester.

**Comment by rsanchez-wsu** [comment]
@cklw5858 Please define what specific things need to be on the wiki page.

**Comment by cklw5858** [comment]
This Wiki page will include the following:
## **Members of Team 7**
**Name:** Carey Kaufmann
**Email:** carey.kaufmann@wright.edu
**GitHub username:** cklw5858
**Slack username:** careyk

**Name:** Logan Rickert
**Email:** loganrickertdev@gmail.com
**GitHub username:** loganrickert
**Slack username:** loganrickert

**Name:** Reggie Ballard
**Email:** ballard.44@wright.edu
**GitHub username:** TheReggieB
**Slack username:** reggieb

**Name:** India Ray
**Email:** ray.85@wright.edu
**GitHub username:** indiaray
**Slack username:** iray

**Name:** Brandon Howard
**Email:** howard.250@wright.edu
**GitHub username:** w012bwh
**Slack username:** w012bwh

**Name:** Nicholas Spencer
**Email:** spencer.119@wright.edu
**GitHub username:** w019ncs
**Slack username:** w019ncs

Milestones
This can serve as documentation to give to the customer / future classes to show the changes that have been done.

Ideas
Any ideas team 7 has. This could be ideas for later in the semester that we can't accomplish right away or even ideas for future classes.

**Comment by rsanchez-wsu** [comment]
@cklw5858 Thanks

**Comment by cklw5858** [comment]
Wiki is now created for Team 7 and added to the table of contents.

**Comment by rsanchez-wsu** [comment]
@cklw5858 Could you provide a direct link for the page here?

**Comment by cklw5858** [comment]
Great idea. Here is the Wiki link for Team 7:
https://github.com/rsanchez-wsu/jfiles/wiki/Team-7
