### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by laurenceforshaw** [rsanchez-wsu/jfiles#244]
#We need to create a tutorial explaining what parts are working and what exactly happens when each main function runs. Detail step by step what exactly the program is doing so that somebody can understand what the program does without diving through the code.

**Comment by ghost** [comment]
Laurence, in your tutorial [#244](https://github.com/rsanchez-wsu/jfiles/wiki/Server-contact-StepThrough) when you write about the addThread() Method in the Server contact StepThrough section of your tutorial. You have a link to another issue about a change to make in the server files to inform the client if they could not connect to the server but still not disconnect anything. Even though you have that link to that other issue would it still be good to in this tutorial to put this in directly to your guide? So someone will know exactly each step the code takes or is supposed to take when it is fully functional? What do you think?

Example: 
"If the server is unable to add in a new client, then the server sends a message to the client that they cant connect then disconnect the client." We still keep the issue link of this in the tutorial though. So we know that is is not  something that is able to be done at the moment but something that will happen when the program is able to work properly. I am sure there is a way to shorten all this wording but I am wondering if this could work.

**Comment by laurenceforshaw** [comment]
My first priority is to document the current functionality or lack thereof. I could add something describing how it should work when fully implemented.

**Comment by ghost** [comment]
Ok for the time being I will continue to read over the tutorial section by section.

**Comment by ghost** [comment]
Your tutorial looks very well formatted and in good detail. I don't see a lot of editing that I think would need to be done. I am going to do a recheck through it all and see if i see any miss spelling or something that could be rewritten in a another way.

**Comment by rsanchez-wsu** [comment]
@laurenceforshaw @GamingFox Where is this tutorial?  Can you provide a link here in the issue so it is documented?

**Comment by ghost** [comment]
Here Is A Link To The Guide Location So documentation can be done: 
[#244_Link](https://github.com/rsanchez-wsu/jfiles/wiki/team-10-Guides)

**Comment by rsanchez-wsu** [comment]
Cool.  Thanks.

**Comment by ghost** [comment]
@laurenceforshaw   The code in the JFilesGui.java looks familiar to me. I recognize some of the code written here in relation from when I did work in Android Studios. For one of my past CS classes. I could work on the Guide for the Gui on what parts of the code is doing if you would like. Would you like me to do some work with the Guide telling about what the Gui does or what the methods do? This code is really similar if not close to exactly like some of the work I had done before.

**Comment by ghost** [comment]
I have been able to add to the Guides and edited the JFilesGui() and added in some description of what this file does. [#244_Gui_Work_part1](https://github.com/rsanchez-wsu/jfiles/wiki/What-Does-The-Public-JFilesGui%28%29-Method-Do%3F) [#244_Gui_Work_part2](https://github.com/rsanchez-wsu/jfiles/wiki/What-Does-The-public-void-start%28Stage-primaryStage%29-Method-Do%3F)

**Comment by ghost** [comment]
I have gone through the tutorial and added in information regarding the JFilesGui.java. I have described each method and telling each step that is done.

**Comment by markbrant621** [comment]
I am closing this issue, as we have made several tutorials in our team 10 wiki, and have linked some of them in the main wiki tab.
