### ISSUE TITLE
Design and Improve Team 10 Wiki Page

### ISSUE THREAD

**Issue by cerasaurus** [rsanchez-wsu/jfiles#245]
Research and design format of team Wiki Page.
Include Sections:

- [x] Team members and info

- [x] Develop and document work-flow/ merge policies

- [x] Ideas

- [x] Work in Progress

- [x] Milestones

Below is a link to the outline I created for our team wiki page. The link should allow anyone to edit it as well.
https://goo.gl/E1FIEo

This issue is considered closed if all five of these sections exist with content.

**Comment by lroberts108** [comment]
I finished the initial work-flow/ merge policies. I think this issue can be closed...

**Comment by rsanchez-wsu** [comment]
@lroberts108 @cerasaurus Please add a link to the project wiki page here.

**Comment by cerasaurus** [comment]
https://github.com/rsanchez-wsu/jfiles/wiki/Team-10
