### ISSUE TITLE
Expand Log4J2 log levels 

### ISSUE THREAD

**Issue by Christofo** [rsanchez-wsu/jfiles#25]
Need to add log levels such as debug, info, system, etc. and log to file.

**Comment by Christofo** [comment]
Issue closed by 59f76d7

**Comment by rsanchez-wsu** [comment]
@Christofo Is this issue really closed?  I don't see how 59f76d7caf187bd1911426398344cdf6277118d1 is really related to the specific change described in this issue.  That commit only adds a single console appender and a single root logger for severity "error".  Can you describe how the additional log levels were added by this commit?

**Comment by Christofo** [comment]
@rsanchez-wsu My error! It is actually closed by bc5d55c15394a871ad37e762b7716b6632d7bca9

**Comment by rsanchez-wsu** [comment]
@Christofo Much better.  Don't forget that it is much easier to reference the issue number in the commit message and GitHub will then automatically link the two.
