### ISSUE TITLE
Formal Command Implementation Structure

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#251]
Our team had a brief meeting today to discuss different ways to implement commands. We felt that an effect way would be to use the [Command Pattern](https://en.wikipedia.org/wiki/Command_pattern).

We propose the creation of a new package called `commands`. There will be a master interface called `command` with the following structure:

```
interface Command {
        Command(Parser p);

        String Execute();
}
```

The `String` returned will be the output from the command being executed. It is expected that this `String` is sent back to the user.

The parser class will be a class dedicated to parsing the given string from the user. An example would be given: `"FIND -r:true -time:10h *.txt"`, the Parser class will automatically parse out the arguments and flags. The definition for the class can be seen below:

```
class Parser {

        // Takes the passed string and parses it.
        Parser(String joinedArgsAndFlags);

        // Returns the arguments for the passed string.
        String[] getArguments();

        // Returns the flags for the passed string.
        Dictionary<String, String> getFlags();
}
```

For the example `"FIND -r:true -time:10h *.txt"`:

getArguments() returns:

```
["*.txt"]
```

getFlags returns:

```
{
        "r": "true",
        "time": "10h",
}
```

Each command implemented (see #231) will be in a dedicated file as it's own class inside of the `commands` package and will implement `Command`. See the following example for the command `Find`:

```
/**
 *  File: Find.java
 */

class Find implements Command {
        String Execute() {
                // Return list of files.
        }
}
````

An example use of the Find command would be:

```
// Input from a user or such.
String input = "FIND -r:true -time:10h *.txt";

Command f = new Find(new Parser(input));
String output = f.execute();
```

In order to complete this issue, we would like to have the following accomplished:

- [x] Create a package called `commands`
- [x] Create and implement a `Command` interface.
- [x] Create and skeleton a `Parser` class (would be inside of the `commands` package.
- [x] Create and skeleton a java class for each command

We would love to hear other's opinions and feedback on this issue. If not much discussion is held, then we will move forward with executing the issue. Please see git branch `commands`.

**Comment by LoganRickert** [comment]
It may be a smart idea to create a convention that all commands start with `Cmd`. IE: `CmdFind` instead of `Find`. There may be conflictions with class names or ambiguity as to what the class does without proper context while scanning through a file.

**Comment by rsanchez-wsu** [comment]
I like the proposal in the summary and the additional idea of a naming convention to reduce ambiguity.  I encourage folks to read Joel Spolsky's blog posting _Making Wrong Code Look Wrong_: https://www.joelonsoftware.com/2005/05/11/making-wrong-code-look-wrong/

It does an excellent job of explaining the concept of Hungarian notation (and how people have misunderstood it).  We might apply something similar starting with our commands.

**Comment by mdgilene** [comment]
If all of the command classes are in the same package, then naming conflicts shouldn't be an issue. An alternative option would to name them like you said `Cmd+name` however internally the command is recognized as simply `name` that way the user doesn't have to type `Cmd`.

**Comment by cklw5858** [comment]
This is a very nice review of what was discussed in the meeting yesterday. Thanks @LoganRickert for writing this up.

**Comment by LoganRickert** [comment]
This issue has officially been resolved. A skeleton for each class has been created.
