### ISSUE TITLE
Reuse slots in clients

### ISSUE THREAD

**Issue by laurenceforshaw** [rsanchez-wsu/jfiles#254]
Currently ClientCount only increments and never decrements. Once enough clients have logged, in no more can do so even is some have since logged out. We need to allow spaces for clients to be reused after clients log out.

**Comment by LoganRickert** [comment]
Our team (team7) has been working on some plans for later in the semester to re work how client connections are handled, which would eliminate this problem.

But yes, this is an issue that should be address. If more than INT_MAX32 clients connect over the life of the server, it would crash the server.

**Comment by markbrant621** [comment]
i will be closing this issue mainly because i believed it was changed awhile ago, but does not have a comment about the changes in this issue. I believe team 7 has fixed the issue, however.
