### ISSUE TITLE
Investigate moving UI development to FXML and SceneBuilder

### ISSUE THREAD

**Issue by mdgilene** [rsanchez-wsu/jfiles#255]
One of the major benefits of FXML is that it allows us to easily split up our views from the controllers and the models behind those views (MVC development pattern). However we aren't fully taking advantage of that at the moment as our views/controllers are mashed together into a single file right now. Using FXML we can easily define the static portions of the user interface and the handlers that go with certain events all in XML format via SceneBuilder (or by hand if you want).  I have mocked up what this kind of implementation looks like and how the code would probably be structured.

This sort of code structure provides for less, cleaner looking code, and allows us to further split the View from the Model.

Link to branch: [fxml-test](https://github.com/rsanchez-wsu/jfiles/tree/fxml-test)

All of the new code is contained in gui.fxmltest

**Comment by SolidStateHero** [comment]
If you don't mind, we'd like to collaborate on this with your team if at all possible.

**Comment by mdgilene** [comment]
GUI development has moved to FXML
