### ISSUE TITLE
Add Basic test server and clientconsoles.

### ISSUE THREAD

**Issue by laurenceforshaw** [rsanchez-wsu/jfiles#260]
Add basic server and client console to UTF over network functions for testing purposes.

**Comment by rsanchez-wsu** [comment]
@laurenceforshaw I think I understand the objective here, but this issue would benefit from a more detailed description for clarity.

**Comment by markbrant621** [comment]
I am closing this issue, as laurenceforshaw has created test classes that do test the server, and i have reviewed these classes and made comments throughout them.
