### ISSUE TITLE
Adding course-specific instructions to the wiki (main)

### ISSUE THREAD

**Issue by burks20** [rsanchez-wsu/jfiles#264]
As an extension of issue #263 (Expand and Restructure Wiki), the Wiki should also include course-specific content such as structures for deliverables.  There should not be a need to cross-reference examples and guidelines from pilot.wright.edu; if the project is only being developed through coursework, the following articles should also exist on GitHub:

- [x] "Course" page explaining how the WSU course is related to this project, with the following sub-headers:
- [x] Guidelines and examples on writing `Milestones`
- [x] Guidelines and examples on writing `Issues`
- [x] Guidelines and examples on `Commit Messages`

The following may also be added:
- [x] Guidelines and examples on `Participation Writeups`
- [x] Introduction to project-related Slack channels

_**NOTE:**_
New pages were created from Issue #263, where the content was not fully developed.  The following pages will require more content:

- [x] Command-Line
- [x] Eclipse
- [x] Eclipse Plugin: Ivy
- [x] Eclipse Plugin: Checkstyle
- [x] Eclipse Plugin: FindBugs
- [x] Eclipse Plugin: DTP (Data Tools Platform)
- [x] Git/GitHub

**Comment by rsanchez-wsu** [comment]
Thanks for tackling this.  It will be a big help to everyone during this and future terms.

**Comment by burks20** [comment]
The Wiki on GitHub does not support a direct file or picture upload of its own.  Since this project doesn't have an official third party storage/content provider, I would rather refrain from using a random one of my choice.  I will be posting images on the Wiki by attaching the pictures through this issue/ticket.  This takes care of two problems:

1.  If I create an image folder in our master branch, it will artificially inflate the project file size.

2.  We do not need to have to worry about reliability of external sites (uptime should be the same between the issue, its attached contents, the project files, and the Wiki where the pictures are inserted).


Therefore, this issue can be closed, but **DO NOT DELETE THIS ISSUE**.  The images are in use over on the Wiki for the project.


For the Wiki page on FindBugs:

- https://cloud.githubusercontent.com/assets/22056291/22898056/ed7a37c4-f1f3-11e6-966c-025160d237ce.png

- https://cloud.githubusercontent.com/assets/22056291/22898058/ed850492-f1f3-11e6-8b4d-af0c87bea9f1.png

- https://cloud.githubusercontent.com/assets/22056291/22898061/ed863a42-f1f3-11e6-8ff3-c48026329a67.png

- https://cloud.githubusercontent.com/assets/22056291/22898057/ed84d684-f1f3-11e6-96a8-ca0bd81f2e6e.png

- https://cloud.githubusercontent.com/assets/22056291/22898060/ed866238-f1f3-11e6-9e28-d0e588128805.png

- https://cloud.githubusercontent.com/assets/22056291/22898059/ed854c4a-f1f3-11e6-8304-34c988c43a2a.png

- https://cloud.githubusercontent.com/assets/22056291/22902548/754f5fee-f203-11e6-9897-f28e987dfd58.png

- https://cloud.githubusercontent.com/assets/22056291/22902655/c39c5fee-f203-11e6-84ad-982fa5ec8827.png

**Comment by mdgilene** [comment]
If the images are just being used for the wiki, then why not just use something like Imgur, rather than cluttering up issues as a storage place for images? As far as reliability and uptime I've never had issues with Imgur and as long as the images are viewed at least 1 time every 6 months they will never be deleted.

**Comment by burks20** [comment]
@mdgilene - I don't think the GitHub Issues has the 6-month restriction like Imgur, so this seems like a better solution.

**Comment by mdgilene** [comment]
Hmm, I'm not sure. It just seems like this is a very hack'y way of doing it. If someone comes along and deletes this issue then all the images on the wiki are gone.

**Comment by burks20** [comment]
More screenshots attached.

For the Wiki page on Course-Related Materials:

- https://cloud.githubusercontent.com/assets/22056291/22900107/37b2ca52-f1fb-11e6-9f43-8cfd22c74fe3.png

- https://cloud.githubusercontent.com/assets/22056291/22900195/763c287c-f1fb-11e6-8896-3c06cb2660b4.png

**Comment by burks20** [comment]
I've made this issue less cluttered by removing the image previews.  I can go further and completely remove the text links to the image files, but it would make it much harder to track down the links.

**Comment by burks20** [comment]
Checkstyle Wiki page pictures:

- https://cloud.githubusercontent.com/assets/22056291/22903706/90569fe2-f207-11e6-9207-a9cb558d4534.png

- https://cloud.githubusercontent.com/assets/22056291/22903952/85bffa5a-f208-11e6-93d9-1f9e7999596d.png

- https://cloud.githubusercontent.com/assets/22056291/22904057/f470f6ca-f208-11e6-9895-515206128613.png

- https://cloud.githubusercontent.com/assets/22056291/22907698/73448eee-f218-11e6-8259-9e2064a7f077.png

**Comment by burks20** [comment]
@hbarri - Thanks for moving this to Milestone 4.  I misjudged the workload and cannot finish all of the objectives within the timeframe of Milestone 3.

**Comment by rsanchez-wsu** [comment]
@burks20 @mdgilene Images can be placed into a directory on the master branch of the project and then referenced from the wiki.  The project code would never be deleted and as long as nobody makes a commit that removes the images, they should never become unavailable.

**Comment by rsanchez-wsu** [comment]
@burks20 @mdgilene Link: https://help.github.com/articles/adding-images-to-wikis/

**Comment by burks20** [comment]
Eclipse Wiki page pictures:

- https://cloud.githubusercontent.com/assets/22056291/23145896/233be572-f7a0-11e6-9dc4-d39cc0d1a84c.PNG

- https://cloud.githubusercontent.com/assets/22056291/23146187/8d630bae-f7a2-11e6-8d33-03d1c9d10adb.png

**Comment by ElderReebs** [comment]
![pasted image at 2017_03_15 05_01 pm](https://cloud.githubusercontent.com/assets/25023452/23972689/1fe700f8-09a9-11e7-8960-9903342dd20d.png) Using for branch wiki page

**Comment by burks20** [comment]
Pictures used on the DTP Wiki page:
-  https://cloud.githubusercontent.com/assets/22056291/24115041/7fdefdc6-0d78-11e7-88d5-86f266694b42.png
-  https://cloud.githubusercontent.com/assets/22056291/24115360/7c84c7b8-0d79-11e7-8b5e-63505aa915d2.png
-  https://cloud.githubusercontent.com/assets/22056291/24115642/665314d0-0d7a-11e7-9038-7ce886612382.png
-  https://cloud.githubusercontent.com/assets/22056291/24115773/d9eac0aa-0d7a-11e7-9ee1-224f81007022.png
-  https://cloud.githubusercontent.com/assets/22056291/24115983/88e54440-0d7b-11e7-8081-9a97483e019f.png

**Comment by burks20** [comment]
Pictures used on the DTP Wiki page:
-  https://cloud.githubusercontent.com/assets/22056291/24116139/17259a34-0d7c-11e7-83fe-66b88da3f48e.png
-  https://cloud.githubusercontent.com/assets/22056291/24116979/d3b0b4c0-0d7e-11e7-82d2-ae3e7242bdf9.png
-  https://cloud.githubusercontent.com/assets/22056291/24117014/ec98bd34-0d7e-11e7-82cb-d20460bc4e50.png
-  https://cloud.githubusercontent.com/assets/22056291/24117038/fabec4ee-0d7e-11e7-8439-eb817a0391f7.png

**Comment by burks20** [comment]
-  https://cloud.githubusercontent.com/assets/22056291/24117188/9a1776a8-0d7f-11e7-8cad-0b9ef4160c7a.png
- https://cloud.githubusercontent.com/assets/22056291/24117664/7fc50f3e-0d81-11e7-9f9e-df28fdc80b42.png
-  https://cloud.githubusercontent.com/assets/22056291/24117613/471065e4-0d81-11e7-809a-31c33fb6de74.png
-  https://cloud.githubusercontent.com/assets/22056291/24117902/4b358d7e-0d82-11e7-8da2-dc9d1aee254c.png
-  https://cloud.githubusercontent.com/assets/22056291/24117948/72e2d3a4-0d82-11e7-8f0c-2d244aa84405.png
-  https://cloud.githubusercontent.com/assets/22056291/24118042/cb622f70-0d82-11e7-9d58-c5449cd98a2c.png
-  https://cloud.githubusercontent.com/assets/22056291/24117993/9ce892a6-0d82-11e7-91b6-520b0781a8b2.png

**Comment by burks20** [comment]
The Git Wiki page was started last week but only contained installation, configuration, and basic commands.  The Git Wiki page was missing the topics of branching and merging, but I had failed to notice that another section of the Wiki addressed these topics (Development Workflow), with contributions from @lroberts108, @mdgilene, @ElderReebs,  and @LoganRickert .  The Git Wiki page now has pointers to the Development Workflow page in reference to the topics of Cloning, Branching, Merging, Push.  Therefore, the Git Wiki page can now be considered complete.

The DTP guide in the Wiki was completed this week.

All outlined Wiki pages for the Course-Related Materials and the Development Environment have been completed.  This issue can be marked completed & closed.
