### ISSUE TITLE
Modify the client/server to use the new command system instead of plain text

### ISSUE THREAD

**Issue by mdgilene** [rsanchez-wsu/jfiles#265]
Currently the Client and Server only respond to user input in the form of plain text. We need to modify the client to create command instances and transmit them to the server, and then modify the server to take the input from the client and rebuild the command instance and execute it.

**Comment by LoganRickert** [comment]
That sounds like you're over complicating things. Right now the client sends the command in plain text to the server. The server interprets the the plain text and transforms it into the appropriate command object.
