### ISSUE TITLE
Incorperate CSS Styling - Document (In wiki) how to format CSS pages

### ISSUE THREAD

**Issue by SolidStateHero** [rsanchez-wsu/jfiles#267]
One of the first steps of moving the hardcoded GUI to CSS is to research and document the steps needed to integrate it with FXML within the wiki. This way, we can have a source of knowledge that others can use when more GUI is added. The information to be added is located in issue #230, issue #255, and issue #247.

This is a child issue of issue #230

**Comment by rsanchez-wsu** [comment]
@willeko999x This issue lacks sufficient clarity.  I get the general idea of what it covers, but it does not go into enough detail that another developer could come along, pick this up and complete the task.  GUI, CSS, and FXML are very broad areas and for this issue to be manageable (and for it to result in useful output) it needs to be thought out a bit more and the end state/deliverable needs to be more clearly stated here.

**Comment by SolidStateHero** [comment]
Closed. The wiki page can be viewed at https://github.com/rsanchez-wsu/jfiles/wiki/Using-CSS-and-FXML

**Comment by rsanchez-wsu** [comment]
@willeko999x Thanks for the link.  It explains everything nicely.
