### ISSUE TITLE
Review & Edit previous Issues

### ISSUE THREAD

**Issue by hbarri** [rsanchez-wsu/jfiles#269]
A lot of issues have been left over from previous semesters regarding non-existent or out-of-date problems in the code. 

- [x] go through all of our issues, especially the older ones
- [x] close the unnecessary issues
- [x] edit the out-of-date but relevant issues

**Comment by hbarri** [comment]
I went through all the old issues, edited the out-of-date issues, closed the unnecessary issues, and cleaned up the old milestones, and then closed this issue.

**Comment by rsanchez-wsu** [comment]
@hbarri Thanks.  I see that there are no milestones remaining from last semester.  I appreciate you making the effort keep the project tidy.
