### ISSUE TITLE
Merge team1 branch into team1-dev branch

### ISSUE THREAD

**Issue by hbarri** [rsanchez-wsu/jfiles#271]
This issue is a continuation of a previous issue we had related to our previous milestone (issue #256). As expected and stated in issue #256,  the team1-dev and team1 branches are significantly different so the merging portion of that issue carried over to this milestone. However, the team1RMI-dev branch was successfully closed in issue #256. We also plan to hopefully be able to merge master into this in later milestones. 

- [ ] merge team1-dev and team1 branches

**Comment by Jdocnog** [comment]
Merged team1-dev into team1.  However, there are still issues that resulted from the merge that need to be fixed in future milestones and issues (such as issue #283).  Commit efcde2b closes this issue #271
