### ISSUE TITLE
'Users' XML Usage

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#274]
So I would like to start an issue about the idea of storing user information as XML.

The rough structure could be as followed:

```
<users>
    <user>
        <username>Logan</username>
        <password>asdf</password>
        <permissions>
            <permission type="admin" value="true" />
        <permissions>
        <directories>
            <directory>data/logan</directory>
            <directory recursive="true">data/tmp</directory>
        </directories>
    </user>
</users>
````

-- Note: recursive="true" means you have access to that directory and all directories below, as oppose to recursive="false" where you can only access files directly in that folder.

Feedback on this XML structure would be great! I am not sure if we want to have this XML-based or database-based. It may be easier to just do an XML-based style right now to remove the need for people to run databases just to test their application.

**Comment by LoganRickert** [comment]
Our team won't really be dealing with this issue but I think it's something important to talk about and handle sooner rather than later so we can start working with persistent servers and other things.

So if another team would like to work on this issue, feel more than free to take it up. Thanks!

**Comment by mdgilene** [comment]
Eventually something like this wouldn't be stored as XML, this information would be contained in a database on the server machine. I was going to look into getting JDBC working, but it does sort of depend on a persistent server.

**Comment by LoganRickert** [comment]
The main reason that I was thinking XML is because it would be easy for people to test and edit the XML so they can easily test permissions, users, etc without having to deal with a complicated database and its interface.

**Comment by mdgilene** [comment]
We could get around that by implementing a `chmod` command that an admin account can use and that command goes and updates the database accordingly.

**Comment by LoganRickert** [comment]
I was assuming that users would be in the head of the server. If you wanted to create a new user, you could without having to create a new user account on the server.

**Comment by LoganRickert** [comment]
`<directory>` could have a property to denote the user has `r` and `w` access as well.

**Comment by rsanchez-wsu** [comment]
@mdgilene The information that we store in the database will likely be XML formatted, at least the serialized representations of the file/directory metadata objects.  It may or may not make sense to treat the user information in the same way.

**Comment by LoganRickert** [comment]
Closed in favor of using a database instead.
