### ISSUE TITLE
Change JFilesServer to a singleton

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#275]
I think it would be a good idea to rewrite the JFilesServer as a singleton. This would ensure that only one instance of the server is running at any given time throughout the program. 

The main reason I would like to do this is to investigate restarting and reloading the server by Class reloading.

This issue will be marked as complete once the class has been changed to a singleton.

**Comment by mdgilene** [comment]
Our team was actually planning on doing some work on the server side of stuff this next week so we can take a look at this issue as well.
