### ISSUE TITLE
Implement Derby SQL query system

### ISSUE THREAD

**Issue by mdgilene** [rsanchez-wsu/jfiles#281]
The purpose of this issue is to implement a system that will allow for the easy creation of SQL statements without having to build them up yourself and (hopefully) be able to use the system without actually knowing any SQL syntax.

The general design will be similar to that of the commands system. There will be 2 master interfaces called `DerbyQuery` and `DerbyUpdate`. Any SQL commands that act as queries will implement `DerbyQuery` and any commands that alter the database will implement `DerbyUpdate`.

### SELECT
  - Parameters:
    - Name of the table to query
    - List of values to get
    - Map of Key/Value pairs that will act as search conditions
  - Return:
    - List of Maps with key/value pairs containing the results. 

### CREATE TABLE
  - Parameters:
    - Name of the table
    - Map of column names and column parameters

### INSERT INTO TABLE
  - Parameters:
    - Name of the table
    - Map of column names and values to insert

### UPDATE TABLE
  - Parameters:
    - Name of the table
    - Map of column names and values to insert
    - Map of Key/Value pairs that will act as search conditions

Note: this will probably change as implementation progresses.

**Comment by LoganRickert** [comment]
What are your requirements to mark this issue as complete?

**Comment by mdgilene** [comment]
This issue is considered closed when there is enough functionality built into the database management system to be able to create and modify tables and to be able to query those tables based on a set of search parameters.

**Comment by mdgilene** [comment]
Once the current changes are merged into master this issue can be closed as the major operations defined above are now possible.
