### ISSUE TITLE
Reorganize Server Package

### ISSUE THREAD

**Issue by LoganRickert** [rsanchez-wsu/jfiles#282]
The server package needs to be reorganized. 

To complete this, the following needs to be fixed:

- [x] The `handle` function should be inside of the `JFilesServerThread` class.
- [x] `JFilesServerThread` is not a very good name
- [x] `JFilesServerThread`'s JavaDocs are a lot of just periods.
- [x] `private JFilesServerThread[] clients = new JFilesServerThread[50];`
- [x] `JFilesServerThread` uses deprecated functions

**Comment by LoganRickert** [comment]
All items have been fixed.

Forgot to add #282 to these commits:

355912c828c2f73ba68d5ce2dc141067d376d3d3
451eee203f36d25857c6d1d3e2162d41e6842153
bfc3097b4393a7bb6776bafd5fcafd83c511210d
0a8592a66249e693ea2d8ea27d6353741983f4ca

**Comment by rsanchez-wsu** [comment]
@LoganRickert Excellent work with this.
