### ISSUE TITLE
Slack Integrations

### ISSUE THREAD

**Issue by inDuberitably** [rsanchez-wsu/jfiles#285]
Design a slack bot that performs the following:
 
1. Notify when assignments/exams are due.
2. Share GitHub milestones in general.
3. Track/assign/resolve Github issues in chat.
4. Get build status and future infrastructure notifications.

**Comment by mdgilene** [comment]
Not sure if you are aware or not but most of those are already available in our slack.

1. Not sure if feasible, due to having to link into Pilot.
3. Already accomplished to an extent via the [Github](https://ceg3120spring2017.slack.com/messages/github/) Slack channel.
4. Already available via [Travis](https://ceg3120spring2017.slack.com/messages/travis/) Slack channel.

**Comment by LoganRickert** [comment]
> Not sure if feasible, due to having to link into Pilot.

Pilot does have an API but I think it's super hard and very restrictive to get access to.

**Comment by inDuberitably** [comment]
-Pilot has demo students who can act as a liaison for getting information to slack. This isn't something necessarily new, logging in and scraping information off a page. No need to actually deal with the garbage that is Pilot's API.
-Github just posts to a channel, not necessarily interacts with it. The goal would be you'd be able to post in chat in your team's channel "@ RaymerBot !issues" (trademark pending) and it'd return to you a list of all the issues assigned to your team. Having it read issues, spill wiki information, and just generally reduce the amount of clutter that occurs on Github from previous classes benefits the entire project's ability to hit the ground running for the next person who interacts with the codebase. 
-I'll grant the Travis builds because there isn't much opportunity to expand on it, but if/when we deploy to an instance on WSU's servers we can have it interact with the main application. "@ jfiles !LS" would return the list of all files in that directory. That's waaaaay down the line though.  

This is about re-interfacing, learning how to interact with Github via other means.

**Comment by markbrant621** [comment]
I am closing this issue was it was part of our teams milestones, and it really can not be picked up by someone else as the work was done mostly by inDuberitably. It also was incomplete and would be even more tough for another student to pick up.
