### ISSUE TITLE
Bring team5file test class over to team10-dev branch

### ISSUE THREAD

**Issue by lroberts108** [rsanchez-wsu/jfiles#290]
Team 5 implemented a filetest class with some thorough comments, see #143 . The test class needs to make its way back into master however since the file restructuring I feel it may be a nightmare. So I plan on only taking the test files created and putting them in our junit test folder.

**Comment by lroberts108** [comment]
I still do not think this will be as productive as I once thought. With branch 5 beginning to create a whole fileapi this does not line up with the current course of development. It is also very difficult to compare since team5 branch still has the old file structure. I will continue to dig through the code but not much longer.

**Comment by markbrant621** [comment]
I will be closing this issue as our mentioned in our slack channel. I believe the overall problem was the files could not be integrated correctly and do not meet our overall goal with JUnit testing.
