### ISSUE TITLE
Clear method

### ISSUE THREAD

**Issue by ianbarney** [rsanchez-wsu/jfiles#292]
As far as I understand, we need to wipe the file images from the gui each time we enter a new directory. As of right now the old images remain and the new directory files show up below the old ones. This is an extension of #266 and the method should be implemented so that the gui can display new directories when they are entered like with #192. The method should be a clear method that removes all the files that are displayed in the gui so the populate method can be called again from the new directory and bring up the new files/directories.

**Comment by mdgilene** [comment]
https://github.com/rsanchez-wsu/jfiles/blob/master/src/edu/wright/cs/jfiles/gui/client/ClientAppViewController.java#L105

The view already does this. this method is called at the very start of `loadDirectory`. Thus every time you need to load a new directory the view will first clear and then re-populate.

**Comment by ianbarney** [comment]
well I must be doing something wrong because every time I call the loadDirectory method with the new directory the files are still there and it shows the new files under them.

**Comment by mdgilene** [comment]
what branch are you working on?

**Comment by ianbarney** [comment]
gui-dev

**Comment by ianbarney** [comment]
okay u rite it's just not in that branch

**Comment by ianbarney** [comment]
my b thanks for pointing that out.

**Comment by mdgilene** [comment]
Seems like master was updated after you branched off of it. `clearView` was added with commit 4f1fa49d5de77f7d9d1fa1463177e562fae6f8c6. I would reccomend merging master into your branch i-order to update it.
