### ISSUE TITLE
Implement Unit Tests for Core

### ISSUE THREAD

**Issue by cerasaurus** [rsanchez-wsu/jfiles#294]
There are many classes in the Core and anyone on the team or another team who is interested in writing JUnit tests can add their name next to a class and write tests for it.  I started with the argument and arguments classes and have that code in Team10-dev (I think).  As discussed in class today, please do not change visibility in order to test. 

Classes in Core:

- [x] Argument - @cerasaurus

- [x] Arguments - @cerasaurus

- [x] CommandLine - @cerasaurus

- [ ] CommandParser - @cerasaurus

- [ ] Environment

- [ ] Error

- [ ] FileStruct

- [ ] FileStructSelection

- [ ] MapEntryConverter

- [ ] SocketClient

- [x] XMLHandler

**Comment by markbrant621** [comment]
I will be closing this issue as it is coming to the end of the class. We were able to complete several of the test cases, but ultimately there was many others we were not able to get to.
