### ISSUE TITLE
Build issues in commands.java

### ISSUE THREAD

**Issue by orangecraz** [rsanchez-wsu/jfiles#295]
I have recently discovered an issue when attempting to build the project. when reading the compiler errors, it appears to originate in Commands.java. I don't know if anyone else is experiencing this issue, but I have been told that the code could be broken. This is important because I cannot work on issue #268 if I cannot build the project

The issue seems to originate in line 37-39, involving end parenthesis. If anyone would like to give any input, please let me know.

**Comment by rsanchez-wsu** [comment]
@orangecraz The proper thing to do when reporting a build failure to post the exact and complete error output.  Only the most trivial problems can be addressed without seeing the actual output of the failure.

**Comment by LoganRickert** [comment]
It is ultra unlikely the commands class is broken in any way. As @rsanchez-wsu said, please post the error output so we can take a lot and hopefully resolve this issue.

**Comment by orangecraz** [comment]
I'm sorry for not outputting the error log. Here are the error messages I was referring to from running the build file.

    [mkdir] Created dir: C:\Users\Michael\git\jfiles\build\classes
    [javac] Compiling 41 source files to C:\Users\Michael\git\jfiles\build\classes
    [javac] C:\Users\Michael\git\jfiles\src\edu\wright\cs\jfiles\commands\Commands.java:37: error: ')' expected
    [javac] 	TOUCH((String[] args) -> {
    [javac] 	               ^
    [javac] C:\Users\Michael\git\jfiles\src\edu\wright\cs\jfiles\commands\Commands.java:37: error: ',', '}', or ';' expected
    [javac] 	TOUCH((String[] args) -> {
    [javac] 	                      ^
    [javac] C:\Users\Michael\git\jfiles\src\edu\wright\cs\jfiles\commands\Commands.java:37: error: '}' expected
    [javac] 	TOUCH((String[] args) -> {
    [javac] 	                       ^

I have put the entire output from my build attempt into a txt file, pasted here.

[error.txt](https://github.com/rsanchez-wsu/jfiles/files/774783/error.txt)

if I'm just doing something wrong, please let me know. My team assured me that it was likely an issue with the code.

**Comment by LoganRickert** [comment]
What branch are you on?

**Comment by LoganRickert** [comment]
Are you using Java 7?

**Comment by LoganRickert** [comment]
I'm 99.9% sure the problem is that you are using Java 7 instead of Java 8. Run Java -version to confirm. Thanks!

**Comment by rsanchez-wsu** [comment]
I am in agreement.  I would be shocked if it were not the case that this is a Java 7 environment.

**Comment by orangecraz** [comment]
It tells me I'm using Java 8.

java version "1.8.0_121"

**Comment by orangecraz** [comment]
I do think it's probably something on my end though.

**Comment by LoganRickert** [comment]
Make sure eclipse is set up to use Java 8 as well.

**Comment by orangecraz** [comment]
I'll check that tonight. That could be it.

**Comment by orangecraz** [comment]
Java's using jre 1.8.0. I'm going to see if there might be a problem with my version of 1.8.0. It could also be a problem with JAVA_HOME. If all goes well, I should have a working build soon.

**Comment by orangecraz** [comment]
JAVA_HOME was set to 1.7. I set it to 1.8, but it's still acting up.

**Comment by orangecraz** [comment]
I have found my issue. JAVA_HOME is set to a jre, not a jdk. I'm going to fix that, and see if that fixes anything.

**Comment by orangecraz** [comment]
I have successfully fixed the issue. I'm closing this issue now. Thank you for your help.
