### ISSUE TITLE
Fixing failed merge of team1 into team1-dev

### ISSUE THREAD

**Issue by hbarri** [rsanchez-wsu/jfiles#298]
We had previously attempted to clean up the team1 branches by merging the team1 branch into the team1-dev branch in issue #271 (commit efcde2b). However, because we are all new to the merging process in eclipse/git, we accidentally merged the team1-dev branch into the team1 branch. This caused us to accidentally push broken code. This issue will be centered around fixing that failed merge by undoing what was done and then merging the team1 branch into team1-dev branch the correct way.

**Comment by mdgilene** [comment]
If you can find the exact commit id for the bad merge `git revert [commit id]` should do the trick and revert the branch to the state before the merge. Not sure how this works though if there have been subsequent commits after the merge.

**Comment by Jdocnog** [comment]
Reverted the Merge of team1-dev and team1 (commit efcde2b).  This revert (commit f62c3ca) rolled team1 back to where it was before the broken code was pushed. This hopefully closes this issue #298.
