### ISSUE TITLE
Update the project wiki with the necessary documentation

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#3]
The Log4J [manual](https://logging.apache.org/log4j/2.x/manual/index.html) is a good place to start.  We need to pare it down to usage and basics to ensure everyone uses the framework the same way.

**Comment by DarthPacer** [comment]
Almost done reading the Log4j Manual, still need to document the needed information into our wiki.

**Comment by DarthPacer** [comment]
Have not had time to update the wiki, will do tonight after class.

**Comment by DarthPacer** [comment]
Accidentally closed the issue.....my bad.

**Comment by DarthPacer** [comment]
I combined the 3 log 4j pages into a singular page. I left the information on error logging, since our log 4j documentation just expands on that. I am closing the issue, however if anyone needs/wants to add additional information to the wiki.

**Comment by rsanchez-wsu** [comment]
@DarthPacer when working issues related to wiki pages, please make sure to include a link to the page.  Also, don't forget that you can create links that show the page diff, which may also be very useful to post to the issue.
