### ISSUE TITLE
Make Juint tests autorun on ANT

### ISSUE THREAD

**Issue by laurenceforshaw** [rsanchez-wsu/jfiles#304]
I believe there is a way to do this. I will attempt to create a wiki page about this then merge tests with the main so that critical function don't break again

**Comment by jtrenton** [comment]
@laurenceforshaw #252 is pretty much the identical to this issue. Maybe close this issue and assign yourself to that issue? And I've played around with modifying the build.xml to some extent, obviously to no avail. Let me know if you want to hear about my failures.

**Comment by markbrant621** [comment]
I will be closing this issue as jtrenton has created the issue as well. I do believe laurenceforshaw has done what he can on his machine to get it to autorun, and with some success.
