### ISSUE TITLE
JFilesGui Information 

### ISSUE THREAD

**Issue by ghost** [rsanchez-wsu/jfiles#309]
This issue is for continuing with the #244 Tutorial Issue but this will be focusing writing out what the Gui section of the project does or is supposed to do when it is fully functional. This will detail the Gui and what each part does and how it works. [Link_To_Guides](https://github.com/rsanchez-wsu/jfiles/wiki/team-10-Guides)

**Comment by markbrant621** [comment]
I like the second part what it is suppose to do. I would suggest ideas for future implementation as the GUI is fairly simple right now.

**Comment by ghost** [comment]
So far I have been able to make good progress in working to describe what the JFilesGui Client part can do. I haven't finished and I still have a ways to go but I have been making progress with writing about how the Gui works and what its supposed to do.

**Comment by ghost** [comment]
I am continuing my work on the issue and hope to have it completed as soon as possible.

**Comment by markbrant621** [comment]
I am closing this issue as GamingFox has made documentation, and this issue was essentially a singular task anyhow.
