### ISSUE TITLE
Directory tree Java bean

### ISSUE THREAD

**Issue by ianbarney** [rsanchez-wsu/jfiles#318]
@elliottfries  and @TremblingOdin believe to complete issue #296 we need to make a java bean class for the Directory Tree that stores the information we need in the directory tree. It should contain the path, stackPath, and image view needed to put it in the gui. This issue is complete when the class is created and contains all the necessary data.

**Comment by elliottfries** [comment]
This issue is being closed because a bean that is useful for issue #296 has already been implemented in the project.
