### ISSUE TITLE
Finish add new user feature on server GUI

### ISSUE THREAD

**Issue by zackarm** [rsanchez-wsu/jfiles#322]
Currently the server GUI has a pop up window that requests information to add a new user to the database, in its current state the information is not actually added to the database. We would like to implement the functionality of this pop up window to add new users to the system. This issue can be closed when the pop up window takes user information and adds the user to the database.

**Comment by mdgilene** [comment]
This issue is resolved as off commit 22868454c340ee46a9a10c43c444ec5bc292fe38
