### ISSUE TITLE
Finalize XML structure

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#33]
In the [XML wiki page](https://github.com/rsanchez-wsu/jfiles/wiki/XML-data-struct), we need to agree on a format and what information we need to send.

**Comment by MichaelMorath** [comment]
I think we should set it up for a Windows host.  I'm open to whatever format we want to use as long as it has everything we need. That said, we should definitely have at least most of the ones in the wiki. We definitely need to track the owner, permissions, when it was last modified,  etc to check access to the file and record changes and size, type, attributes, etc  to check how it is used and how large it is.  Beyond that, i'd say it just depends on how much detail we want.

**Comment by rsanchez-wsu** [comment]
@MichaelMorath What do you mean by "set it up for a Windows host"?

**Comment by MichaelMorath** [comment]
@ranchez-wsu like we said in the wiki, the metadata we track may be slightly different depending on what operating system we have in mind. Permissions being a good example. I'm simply suggesting that since this file browser of ours is fairly simple, we keep Windows in mind when considering what metadata to track as it would be a good basepoint.

**Comment by bdenlinger** [comment]
@MichaelMorath @rsanchez-wsu Java.nio.file.attribute.BasicFileAttributes is platform independent.  Sub interfaces exist for POSIX and DOS system specific attributes.  The DTD can allow for those as optional elements.

We should plan on this being platform independent, in my opinion.

**Comment by bdenlinger** [comment]
@MichaelMorath @rsanchez-wsu Also something that I just thought of, DOS file attributes are support by filesystems like Samba.  I don't believe the reverse is true in Windows.  I believe that means we might have to move the system attribute down so that each item has it's own system?!

**Comment by MichaelMorath** [comment]
@bdenlinger Sounds good. I don't know why I didn't think of simply enumerating the options in the DTD to work for multiple operating systems.

**Comment by bdenlinger** [comment]
We need to commit this to the wiki.  Once we do that we can close.

**Comment by DarthPacer** [comment]
This seems to be completed, when reading the wiki, we have a permissions tag that have the options of Linux and windows. In the DTD, we would make those enumerated options and we should be good. I believe we can close this issue.
