### ISSUE TITLE
Document and/or repair permissions.

### ISSUE THREAD

**Issue by laurenceforshaw** [rsanchez-wsu/jfiles#331]
Currently attempting some commands gives a no permission error in master. Permissions are not documented in the primary wiki. How to use to get authorization needs to be documented and/or fixed if it is working wrong.

**Comment by LoganRickert** [comment]
Logan Rickert [8:27 PM] 
Permissions for the server are now operational. If you are getting permission denied for right now, just run the command `login "Bill Gates" windows_vista`

**Comment by LoganRickert** [comment]
This 'issue' has been resolved code wise. It now logs the user in as the 'tmp' user, defaults to the tmp directory and gives them full read/write access.

The wiki documentation still needs to be added.

**Comment by markbrant621** [comment]
I will be closing this issue as it has been resolved by LoganRickert.
