### ISSUE TITLE
T5-M2-I1: Finish JFile

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#34]
# T5-M2-I1: Finish JFile
## What

Team 5 shall finish creating the JFile class's core methods and begin work on methods for other teams. In finishing the class, the team shall also work on refining the definition and purpose of the class as well as implementing any methods that other teams have readied for use in the File API. Since the JFile class is way ahead from the last milestone, this class needs to focus on how it is implemented, and consider 
## Why

The JFile class is at the core of the File API. Everything hinges on how this class works, so how this class works determines how the entire File API will work.
### See:

<ul>
 <li><a href="https://github.com/rsanchez-wsu/jfiles/wiki/Milestone-1-Objectives#t5-m1-i1-creating-the-jfile-class-11">Wiki Reference to the Original Class Requirements</a>
 <li><a href="https://github.com/rsanchez-wsu/jfiles/issues/11">The Original Issue this Issue is Continuing</a>
</ul>

**Comment by Dorkatron199** [comment]
@BrandAllred @srodriguez4 
Once Sergio rechecks this file, this issue can be closed. Additionally, the file ca then be pushed up to our "main" branch for our team, the team5 branch. I suggest closing this issue only after JFile gets pushed to our main, which will only happen after Sergio checks the file.

I would also like to thank Sergio again for his help. We would not be making this progress without it.

**Comment by BrandAllred** [comment]
We, as a team, feel that JFile is fully completed. We will edit as needed, following the communication with others teams.

issue #34 is now closed.

**Comment by rsanchez-wsu** [comment]
@Dorkatron199 @BrandAllred @srodriguez4 was the file referenced in John's comment ever checked and pushed?
