### ISSUE TITLE
Fix issues with errors, findbugs, and checkstyle for the new merged branch

### ISSUE THREAD

**Issue by jasonmarcum** [rsanchez-wsu/jfiles#345]
Since we now successfully merged the branches in commit 482741d, we plan to go in and fix any errors that occur and issues in the code with findbugs and checkstyle.

**Comment by Jdocnog** [comment]
I fixed some Checkstyle and Findbugs errors for this milestone I think because it has to be done beforehand for us to be able to push working code.  This was done on commit 6d16706.  It fixed all the Logger errors within most of the code for Team1-dev so that we can fix those findbug errors.

**Comment by hbarri** [comment]
@jasonmarcum and I went through the code and fixed all the errors, findbugs, and checkstyle issues for the new merged branch in commit 4febddb, closing this issue
