### ISSUE TITLE
Make the login properly change permissions.

### ISSUE THREAD

**Issue by laurenceforshaw** [rsanchez-wsu/jfiles#353]
Make logging in correctly change what permissions a user has.

**Comment by LoganRickert** [comment]
This should already happen.

**Comment by laurenceforshaw** [comment]
It does not change the cache permission type. However looking at it the cachepermissiontype looks like dead code. Maybe just remove that variable?

**Comment by markbrant621** [comment]
closing this issue as i know it was either finished or mostly completed. Regardless it does not need to remain open for a future class due to the lack of detail on what laurence ultimately wanted.
