### ISSUE TITLE
T5-M2-I3: Integrate Logging Into the File API

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#36]
# T5-M2-I3: Integrate Logging Into the File API
## What

Team 5 shall integrate the logging software made by team 2 into the JFile API. The team shall have at least one member who focuses on learning how to use it who the team can turn to. This member will work with the team members who are working on specific classes to get the logging software implemented in those classes. Since JFile is mostly finished, that class should be done first.
## Why

This will be necessary for both troubleshooting, especially once the API is implemented in the JFiles program, as well as documentation. It is also required to meet the standards of the rest of the teams. Additionally, having one member who knows the logging software very well will undoubtedly prevent many pitfalls in the future.

**Comment by Dorkatron199** [comment]
With my commit that pulled log4j into our API, I consider this issue complete. It has been passed on to the next milestone at #65. Now, Sergio needs to read through team 2's wiki and documentation and try to get this working in JFile if possible. It may not be possible at the time, since JFileManager may not have enough to start implementing logging software and JFile may not have as much to log... For this reason, I will make sure to find extra work for him to do and have backups prepared. I will not create these into issues unless the log4j becomes invalid to avoid assigning to much work to one milestone.

**Comment by rsanchez-wsu** [comment]
@Dorkatron199 Please identify the commit that you believe completes this issue.  Also, please note that it is OK to move an issue from one milestone to the next instead of closing the issue and creating a new one.

**Comment by Dorkatron199** [comment]
ce852a9,    eb38dd9 (now)

I don't know/remember what commit I was talking about then, but it is definitely done by now. I have also started moving issues on to new milestones more often now, unless closing seems more appropriate. Can I close this issue now?

I apologize if this sounds blunt, I'm typing this a 2:00 AM... It isn't meant to be.

**Comment by rsanchez-wsu** [comment]
@Dorkatron199 No worries.  It is a learning process for all involved.
