### ISSUE TITLE
T5-M2-I4: Create Integration Comments

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#37]
# T5-M2-I4: Create Integration Comments
## What

Team 5 shall communicate with other teams and create comments in the JFile and JFilemanager classes detailing which teams will have methods that need to be integrated into which methods in these classes. An example of this would be networking methods needing to be integrated into copy and pasting methods. This could also be security methods needing to be implemented during any JFileManager operation. These should be regular comments, not part of the java documentation, as these will be for internal use and are thus temporary.
## Why

This needs to be done so that Team 5 can keep in mind what teams need to be coordinated with for what methods. This is especially important for methods that have not been made yet so that team 5 does not forget to go back and add in those methods when they are finished. The comments will be removed once the appropriate methods/implementations are added.

This mostly needs to be done so that Team 5 can know what methods in the File API are important to what teams, so that Team 5 can coordinate better later on. This can also be created via a list in the wiki page was well, so that the information can be listed in a quick, easy-to-read manor by both team 5 and other teams.

**Comment by Dorkatron199** [comment]
Jonathan Joyce (@joyceje) from Team 1 has just discussed with us on Slack regarding collaboration.

Team 1 is planning on implementing the actual network transfers, so we need to coordinate with them on what will be transferred. This is necessary for both teams. Team 1 needs this so that they can make their code transfer JFile objects, while Team 5 needs it so that they can better tailor JFile to Team 1's needs (this is relevant to @BrandAllred) and determine where in JFileManager Team 1's methods will be needed (this is relevant to @Dorkatron199).

In this discussion, I helped clarify where I am planning on our project going and the role of our API as it relates to other team's APIs.

---

<b>John Wintersohle</b> via <a href="https://ceg3120fall2016.slack.com/archives/team5/p1475891799000034">Slack</a> @ <i>9:56 PM on 7 Oct. 2016</i>:

> My goal for JFileManager is for it to kind of work as a unifying class. I hope for it to take JFile, server methods, security, and all things that go into copying, pasting, etc. and puts them together to make a well-developed, easy to use system for the GUI teams. It also means that future teams would, in theory, be able to make different GUIs for the same back-end.
> 
> Basically, I am planning on JFileManager as being a middle-ground between the back-end (which actually handles all of the security, networking, internal management, etc.) and the front-end (the GUI or CLI, as desired by the front-end teams; we know the're making a GUI, but this would mean that a CLI could also be made from this).
> 
> My purpose for doing this is so that our system can be as flexible as possible, ans still maintain relatively well-separated roles. JFileManager will use whatever  Team 1 determines is necessary for use in its methods (copy, paste, cut, etc.). Having comments for what team to go to for what methods is one of our issues, so I will have to go over your code and review which of JFileManagers code will most require collaboration with you. See issue #37 (T5-M2-I4: Create Integration Comments < [URL for the Issue] >)

It is also important to note that I made the above plan before Prof. Sanchez (@rsanchez-wsu ) expressed concerns with going into too much depth with this separation-of-ends (front/middle/back) concept. It was my thought, at the time we came up with File API idea, that this would be useful later on. If we determine that there is a better way, we may go down that path if we can feasibly make that transition in time.

So far no one has expressed concerns with this idea, and I think that this will definitely be useful further down the road, both for this projects and possible future projects.

**Comment by Dorkatron199** [comment]
Only JFile is left. Since this is so, I will not re-up this issue in the upcoming milestone.

**Comment by BrandAllred** [comment]
The comments are not necessary in the JFile. I, and the other members of team 5, are going to be working closely with the other teams.
