### ISSUE TITLE
Merge team12 development branch into master and delete development branch

### ISSUE THREAD

**Issue by zackarm** [rsanchez-wsu/jfiles#371]
We need to clean up our development branch so that it can be merged with master and delete the branch because the semester is coming to an end. As of now there are a few errors that need to be fixed and most likely some checkstyle violations. This issue can be closed when the team12dev and team12 branches have been successfully merged into master and deleted.

**Comment by mdgilene** [comment]
All team12 branches have been merged into master and deleted
