### ISSUE TITLE
T5-M2-I6: Get Ant Working for at Least One Team Member

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#39]
# T5-M2-I6: Get Ant Working for at Least One Team Member
## What

Team 5 must have to have at least one individual capable of checking the File API with Ant. The team doesn't have to check when pushing to team5_dev, but it does have to be able to check before pushing to team5 (main) or master. This individual may also be able to help other team members get Ant working.
## Why

Ideally, the team should be able to have all members check their code before even pushing to dev, but as long as the team has one member who can check before pushing to main or master, the team can at least function; there will just be a lot of emphasis on the one individual who can check via Ant.

**Comment by srodriguez4** [comment]
**Was able to get ant working**
**Problem:** Had issues with setting path on Windows 10
**How to fix this problem on Windows 10:**
- In Cortana, search 'variables' (system properties window will open)
- Click on Environmental Variables
- Double Click on 'PATH' in the bottom pane
- Click on 'New'
- Once 'New' is clicked, it should make a space at the bottom for you to add a path
- Add the Whole path to where you stored Ant/Ivy all way to \bin, for example, mine was C:\Users\sergio\Documents\CEG 3120\apache-ant-1.9.7\bin, thus I added that to my PATH

**Comment by rsanchez-wsu** [comment]
@Dorkatron199 @BrandAllred did either of you manage to get Ant working from the CLI?  It should be trivially easy and every member of the team should have it working.  If you are experiencing difficulty please hit me up in Slack and I will try to help you sort it out.
