### ISSUE TITLE
Collaborate with Team 5

### ISSUE THREAD

**Issue by tytrip** [rsanchez-wsu/jfiles#40]
We need to collaborate with Team 5 to determine what a JFile object looks like and what data it contains. This JFile object is what we will be sending in XML format, so we need to have a thorough understanding of what this datatype is

**Comment by tytrip** [comment]
Upon further analysis, I do not believe this issue is relevant to our current milestone. Our XML files will be made up of the file system on the server, not of an actual JFile object. Therefore, I am marking this issue as complete.

**Comment by rsanchez-wsu** [comment]
@tytrip I added the invalid label.  If an issue is deemed not worth fixing or not valid, it is best to apply an appropriate label to distinguish it from legitimate issues that have been or are being addressed.  As the number of old issues continues to grow it will help future developers on the project get a better idea of the project's history.
