### ISSUE TITLE
Increase Checksum Functionality on Both Sides

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#47]

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github This issue needs a proper summary (I am not even sure what it means to increase the checksum functionality), a clear description of the work to be done, and set of defined criteria that capture the desired end state.

**Comment by Swilloughby-github** [comment]
This issue is far outdated and poorly summarized. Checksums have been implemented in the program at this point, so this issue should be closed.
