### ISSUE TITLE
Checksum Client Implementation

### ISSUE THREAD

**Issue by joyceje** [rsanchez-wsu/jfiles#49]
Added Client checksum of the newly created file compare the 2 and display the results

**Comment by rsanchez-wsu** [comment]
@joyceje How is this issue distinct from #47? Also, please see my comment to @Swilloughby-github on that issue. The same things apply to this issue.

**Comment by Swilloughby-github** [comment]
Our program appears to have working checksum functions. This issue seems to be outdated, so I'm closing it.
