### ISSUE TITLE
Differentiate types of buttons.

### ISSUE THREAD

**Issue by matthews92** [rsanchez-wsu/jfiles#50]
We will need two different general types of buttons for clicking a file or a folder that will send different requests to the server. When clicking a file, a request should ask the server to download or open the file. When clicking a folder, a request should ask the server to see it's contents.

If the user double clicks on a file, this should request the file from the server and download it to the client.

If the user double clicks a folder it should request the new path from the server and display what is in that directory to the user.

Caching can also be considered here (i.e. if the user goes to a folder they have already been to, it should load that information from cache and not query the server again).

In order to implement this we will need to finish issue #17, from milestone 1. That issue collects data from the server to fill the GUI with different folders and files, then based off of what is clicked it can be determined what type of request is sent to the server.

**Comment by rsanchez-wsu** [comment]
@matthews92 This issue could use a bit more detail and a clearer statement of the end state.

**Comment by matthews92** [comment]
This issue consists of a bunch of smaller issues that would all need separate issues that could each be large issues on their own. Not all of these concerns are directly related to the GUI and could already have work on them from other teams. It would be better to have the next development teams to create these issues on their own as they come to them rather than create them now.
