### ISSUE TITLE
Collaborate with team 2.

### ISSUE THREAD

**Issue by matthews92** [rsanchez-wsu/jfiles#51]
When making requests to the server there could be multiple errors from the connection being lost to the file requested not being found. Our team will collaborate with team 2 and their established error logging to have consistency in error logging and prepare for planned advancements in the GUI that may make use of this resource.

**Comment by MichaelMorath** [comment]
Did you look at our wiki entry? https://github.com/rsanchez-wsu/jfiles/wiki/Error-Logging it should help you understand how it works.

**Comment by rsanchez-wsu** [comment]
@matthews92 This issue doesn't actually describe any work to be done, other than a very vague collaboration.  Please either make this issue specific or close it as invalid.
