### ISSUE TITLE
Discuss GUI design and functionality with Team 3

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#61]
Due to the similar nature of team 6’s and team 3’s work overlapping, duplicated, and similar coding will likely occur. To avoid this a line of communication should be established between the two teams, and team 6 should keep up to date on team 3’s portion of the project.

**Comment by rsanchez-wsu** [comment]
@btdugas What would be the objectives of such a discussion?  Perhaps you should invite some of the team 3 folks to contribute some objectives to the discussion ahead of time as well.  Remember to be specific and to be clear with the statements about what is to be done.

**Comment by SasquatchMighty** [comment]
In closing issue #19 we also addressed this issue.
Team 3 and Team 6 are collaborating on the projects GUI designs. On our joint slack page named “gui_collaboration” (https://ceg3120fall2016.slack.com/messages/gui_collaboration/) there is a simple list of GUI features drawn from both teams’ wiki pages. The list is currently divided into priority features and secondary features. Priority features are things we believe need to be implemented if our GUIs are to be respectable. The secondary list is a list of features that will polish the GUIs but are not crucial to the projects operation. 
A special thanks to team 3s nickwvr (SlackID) for his initiative.
