### ISSUE TITLE
Design an icon to represent files

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#62]
Create an image that will represent a generic file on the Client Side GUI. The image is meant to be a thumbnail image so it will be small. This means it should have very little detail and be simple design.

**Comment by rsanchez-wsu** [comment]
@btdugas Please have a look at #50 and coordinate with team 3 to make sure that there isn't unnecessary duplication of effort.  FYI: @matthews92

**Comment by SasquatchMighty** [comment]
masters1222 of Team 3 has created icons that will meet our needs. They are located at on the team3-dev branch. jfiles\src\gui\img
![file_icon](https://cloud.githubusercontent.com/assets/14119599/20022017/efc74f92-a2ae-11e6-9d86-b1527347dc88.png)
