### ISSUE TITLE
Design an icon to represent folders

### ISSUE THREAD

**Issue by btdugas** [rsanchez-wsu/jfiles#63]
Create an image that will represent a folder on the Client Side GUI. The image is meant to be a thumbnail image so it will be small. This means it should have very little detail and be simple design.

**Comment by rsanchez-wsu** [comment]
@btdugas Please have a look at #50 and coordinate with team 3 to make sure that there isn't unnecessary duplication of effort. FYI: @matthews92

**Comment by ghost** [comment]
We should talk about what kind of theme do we want for this GUI. We could make completely custom icons or we could use glyphicons possibly. These are already created for us in open source projects. My personal favorite is: http://fontawesome.io/icons/. There is also a bootstrap version of this: http://getbootstrap.com/components/. Just some ideas for now.

**Comment by rsanchez-wsu** [comment]
@cspencer44 I'm all for reusing what is out there already.

**Comment by AlexDespain01** [comment]
@btdugas Could you take a look at the slack GUI collaboration channel? I just uploaded a few folder and file icons. You can see them here as well https://github.com/rsanchez-wsu/jfiles/tree/team3-dev/src/gui

**Comment by SasquatchMighty** [comment]
masters1222 of Team 3 has created icons that will meet our needs. They are located at on the team3-dev branch. jfiles\src\gui\img
![folder_icon2](https://cloud.githubusercontent.com/assets/14119599/20021979/ca96c662-a2ae-11e6-93b1-a63f47ba437c.png)
