### ISSUE TITLE
T5-M3-I1: Opening Files with Particular Applications

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#64]
# T5-M3-I1: Opening Files with Particular Applications
### open(JFile file)

The open(JFile file) method is expected to open a file with a default application as defined by a config file. There has been quite a bit of debate as to how the file of this config file should be and how this method shall work as a result. This is mostly due to different OSs handling this subject differently. This will require further investigation in order to be worked upon.

We expect the config file to be in XML. The general structure should be simple, a file type is mapped to an application, but how file types and applications are found/categorized is the sticking point. For this, we have been looking into the Runnable interface for determining whether a file is an application or not. We have also discussed briefly how to handle determining file types on Linux.

This method should throw errors if the application is not set, if the default application is not an application, if the file type is not recognized, and if the default application cannot open the file type. Ideally, each of these would be avoided during file/application assignment, but must be accounted for either way. One option for handling a missing file-application association is to just have the method pull up a GUI asking for a different application and have the user choose the program.
### open(JFile file, Application app)

The open(JFile file, Application app) needs to be able to take in a JFile some application and open the file in the application. This carries many of the same issues as above. It does not carry the concerns of the configuration file not being preset, but has more emphasis on whether the application passed in is genuinely runnable and can take in the file as a parameter.
## Why

This issue is made in response to issue #35, which turned out to be too broad and undo-able. This, is more feasible. In #14, Sergio did research into various classes that may be able to help with these methods. He will, thus, be expected to help with this issue. These are two methods that should be workable without anything needed from other teams. This basic functionality is expected for any file browser, so it should be expected for ours.
## Minimum Requirements for Closure

In order to close this method, the team must have at least found a way to implement these methods. If the team is in the process of implementing the idea when the deadline passes, it can be finished in the next milestone, but this milestone is defined by at least having a way to implement these methods.

**Comment by Dorkatron199** [comment]
I think this issue may take some research in order to do. I think I may look into a different issue that I can actually get work done now. However, in the wake of our recent JavaBeans information, I have a better sense of what I want JFiles to do and what needs to be left to other teams. The open and openWith methods will most likely call network methods that open files. Network methods will handle movement of content, while our API will focus on unifying APIs together and transferring of metadata.

To this end, I think having a workingDirectory field is a more important issue to tackle. I will create an issue for that and come back to this at a later time. Also, Brand has a bit more know-how in regard to operating systems, and how they detect various things. He would be a better match for this issue...

**Comment by rsanchez-wsu** [comment]
@Dorkatron199 One thing that you might consider as a "quick" approach to the idea described in this issue is the use of a `ProcessBuilder`.  You can basically use the `Application` object to construct a command line n a `ProcessBuilder` that then gets executed in the system shell.

**Comment by Dorkatron199** [comment]
@rsanchez-wsu  Thanks. I will look into it.

**Comment by Dorkatron199** [comment]
@rsanchez-wsu I added documentation explaining some of the details of this into the code for whoever gets to developing it. It may take a little bit of tinkering, but it should work. Thank you very much for your support.

Brand is much more familiar with OSs, so I may still ask him for aid, but this helps greatly.

This may even be relevant to what I was planning to do instead of this issue, which may change how that issue will be done, so this will have long-term affects on the File API.

**Comment by Dorkatron199** [comment]
I will close this issue and open up a new one for testing what you have shown me in the new milestone.
