### ISSUE TITLE
Figure out what is needed to push to master

### ISSUE THREAD

**Issue by joyceje** [rsanchez-wsu/jfiles#69]

**Comment by rsanchez-wsu** [comment]
@joyceje This issue contains no useful information.  Please update with a description of what needs to be done and what criteria need to be met.

**Comment by w030mao** [comment]
We have implemented a way to send a file from the server to client and would like to push this to master so other teams can see how we are doing this.  First we will need to merge master with the team1 branch to get the logging commits from team2. Then we will need to clean up our code on dev and merge our team1-dev branch to team1 and ensure it works before merging to Master.

**Comment by rsanchez-wsu** [comment]
@w030mao Could you mention the specific commits that implement that capability so that they are linked to this issue?

**Comment by rsanchez-wsu** [comment]
@joyceje What was the rationale for closing this issue?  Was it completed?  If so, how?  If not, why/how was the decision made to close and what is the follow-on plan if any?
