### ISSUE TITLE
Start work on a Java bean to encapsulate JFiles

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#72]
The class will consist of some basic methods to read the data from the bean like current path, number of objects, etc.  It will also consist of a serialize and deserialize method.

**Comment by rsanchez-wsu** [comment]
@bdenlinger Please flesh out this issue with a more robust statement of the objective, work to be done, and completion criteria.

**Comment by tytrip** [comment]
A duplicate issue (#75) has been created for this. Since the duplicate issue has relevant sub-issues attached to it, I am closing this. All future work on the Java Bean should reference #75.
