### ISSUE TITLE
Integrate team 2 and team 5 code base

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#73]
The JFiles API and classes work needs to be integrarted into our code base because it provides the structure for what data is transmitted.

**Comment by rsanchez-wsu** [comment]
@bdenlinger Please describe in more detail what needs to be integrated, what "integrated" means in this context (merged into a particular branch?) and what criteria will be met when the work is complete.

**Comment by tytrip** [comment]
This issue was completed via commit d6eed6146b5811655e7294d79975aff8aab371b8. Team 2 and Team 5 now have a collaboration branch named "team-2-5-dev".
