### ISSUE TITLE
Finish File-Receiving for Client

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#79]
Write code in the client side that makes it able to receive a file sent from the server.

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github This issue requires considerably more detail.

**Comment by Swilloughby-github** [comment]
Okay. So, at the time I first posted the issue, there was no code in the client that would allow it to receive bytes from the server and output them to a new file. The idea I had was that the client needs to be able to get these bytes that the server sent and output them to a file, and then validate the new file's checksum against that of the original to make sure no changes were made. The method should then be able to print whether or not the transition was successful, depending on the result of the checksum.

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github Thanks
