### ISSUE TITLE
Add recursive search and partial search options

### ISSUE THREAD

**Issue by kryan100** [rsanchez-wsu/jfiles#83]
On the server side, we'll utilize either iterateFiles or listFilesAndDirs from java.io.File to add the ability to search through all child folders. iterateFiles returns an iterator and listFilesAndDirs returns a Collection of all files which matched the FileFilter specified.  

For partial search options we can use the WildcardFileFilter, and wrap each search within "*" 

Update 1:
Abandoned iterateFiles and listFilesAndDirs as the already existing DirectoryStream has a constructor that allows search patterns to be passed into it. These patterns can contain glob patterns which should be an acceptable alternative to regex for our purposes.

For recursive searches a second method recursiveFindCmd() will be added. This method will recursively find all child folders then run the normal findCmd() method on each one.

On the client side. The FIND command will still work the same as before, but will support glob patterns. For a recursive search, the user should input FINDR instead, followed by their search pattern. FINDR will be listed as a separate command on the server side.

**Comment by rsanchez-wsu** [comment]
@kryan100 Please don't forget to describe the command/protocol that the client will need to use to access this recursive or partial search.
