### ISSUE TITLE
Create search history logging on client side

### ISSUE THREAD

**Issue by kryan100** [rsanchez-wsu/jfiles#85]
A search history log will open new possibilities for future features such as search recommendations based on frequent searches. This can be done by appending a search to a text file before sending it to the server to process.

**Comment by bdenlinger** [comment]
This sounds like a perfect excuse to do custom logging levels in log4j!

**Comment by rsanchez-wsu** [comment]
@kryan100 This should be configurable in the client configuration.  Please make sure to add information to the description for this issue to capture any new configuration options(s), sensible default values, valid values, etc.

**Comment by JDampCoder** [comment]
Closed because this completes the issues description and appends text to the history.
