### ISSUE TITLE
Adjust handling of XML configuration files

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/jfiles#87]
@bdenlinger Based on the commit (ca18c7f) that implements the parsing of serverConfig.xml, I realized that we need something a bit more suited to what we are doing.  I would like for you (and your team) to make a few changes to the XML file handling:
- Remove `serverConfig.xml` and `log4j2.xml` from the repository
- Replace them with example files, perhaps in an examples directory
- Have the program look for the files in several standard locations:
  - `/usr/local/etc/jfiles/serverConfig.xml` & `/usr/local/etc/jfiles/log4j2.xml`
  - `/opt/etc/jfiles/serverConfig.xml` & `/opt/etc/jfiles/log4j2.xml`
  - `/etc/jfiles/serverConfig.xml` & `/etc/jfiles/log4j2.xml`
  - `C:\Program Files\jFiles\etc\serverConfig.xml` & `C:\Program Files\jFiles\etc\log4j2.xml`
  - `$HOME/.jfiles/serverConfig.xml` & `$HOME/.jfiles/log4j2.xml`
- If no configuration file is found, have the application start with sensible defaults and emit a message to the console indicating that it is running without configuration files
- Document in the wiki and README.md where to grab the example files, how and what to customize, and what the application defaults are

If you have any questions, please let me know.

**Comment by bdenlinger** [comment]
I agree with the issue regarding the server config.  The log4j2.xml is little more difficult.  It is apprently possible to reconfigure the xml location from within the class, but [LoggerContext class is not part of the public API so your code may break with any minor release](https://logging.apache.org/log4j/2.0/faq.html#reconfig_from_code).

I changed it once when I moved it.  It's a settings change within the "Java Build Path" under the Properties menu.  I honestly can't find it now.

**Comment by rsanchez-wsu** [comment]
@bdenlinger Thanks for looking into this.  I'll also assign myself to this issue and have a look at the log4j2.xml part.

**Comment by tytrip** [comment]
@bdenlinger @rsanchez-wsu Just throwing this out there - would there be any benefit to passing the properties file to the program via a start script? The start script could pass the file to the jar via cmd line. This way we wouldn't have to define several locations to search for it. During development we can simply pass it via an Eclipse run argument

**Comment by bdenlinger** [comment]
Found the config file parameter location.  It's a VM argument.
![image](https://cloud.githubusercontent.com/assets/21348151/19398058/c391b404-9218-11e6-8e93-144750ae8730.png)

**Comment by bdenlinger** [comment]
@rsanchez-wsu Having some issues with finding a file that I know exists.  Current code looks like:
![image](https://cloud.githubusercontent.com/assets/21348151/19398506/faa005a2-921a-11e6-8259-8d2fbf6e870a.png)
I also tried:

```
if (new File(configPaths[i]).exists()) {
...
```

**Comment by rsanchez-wsu** [comment]
@tytrip @bdenlinger I am OK with allowing the user to specify the configuration file path via the command line.  However, I also feel strongly that the application should look in "standard" locations as well.

**Comment by rsanchez-wsu** [comment]
After reviewing this issue and #141, it seems like the CheckStyle problem with log4j2.xml should be handled separately.  That is the nature of #141, so I am closing this issue and the CheckStyle piece can be handled under #141.
