### ISSUE TITLE
Handling invalid input

### ISSUE THREAD

**Issue by kryan100** [rsanchez-wsu/jfiles#89]
Currently if the user input includes the FIND command, it is split into an array with the second value holding the search pattern. However, if the FIND command isn't followed by a search pattern, the program will throw an IndexOutOfBounds exception as there would be no second value.

If FIND is input without an argument the (Client? Server?) should alert the user instead of trying to process the request.

**Comment by rsanchez-wsu** [comment]
@kryan100 Nice job with this issue.  It is clear what needs to be done and when the work would be considered complete.

**Comment by bdenlinger** [comment]
Commit c24929e6b3de8332b566b529cfaef76d883e51c9 contains an error.  The while loop loops for ever if valid input is received.  An if is appropriate here.

**Comment by bdenlinger** [comment]
Working on this with @viro101 .
