### ISSUE TITLE
Expand on search command

### ISSUE THREAD

**Issue by ChronoAnomaly** [rsanchez-wsu/jfiles#9]
Adding in more functionality such as recursive searching from a directory or by passing a path to start searching from. This could also be expanded into a secondary command from the basic search command.

**Comment by Swilloughby-github** [comment]
It seems that the issue itself is solidly defined, but it depends on the completion of another issue within the same milestone, which is something I personally wouldn't do.

**Comment by rsanchez-wsu** [comment]
@ChronoAnomaly Please give this issue a more detailed description, along with a clearly stated set of criteria that define when the work is complete.

**Comment by kryan100** [comment]
Although the issue is vague, commit https://github.com/rsanchez-wsu/jfiles/commit/51bdd660919fef3f74698680d2a5bc46b040431a has been determined to adequately accomplish the intended functionality defined in this issue.
