### ISSUE TITLE
Client creates TXT-COPY file

### ISSUE THREAD

**Issue by Swilloughby-github** [rsanchez-wsu/jfiles#91]
When the client calls the server's sendFile method, it seems to receive the bytes from the command. It needs to create a file identical to the one it requested, only with "-copy" appended to the filename. When ran, the code creates a new file in the form of "filename.txt-copy", which is an invalid file type. This issue is considered fixed when we can get it to create a file in the form of "filename-copy.txt".

**Comment by rsanchez-wsu** [comment]
@Swilloughby-github Nice work with the description.  Is the objective of appending -copy to prevent a name collision on the client side?

**Comment by Swilloughby-github** [comment]
@rsanchez-wsu I assume so. I think Michael wrote the comments for the client's fileCommand, and he wrote that the new filename should have "-copy" appended at the end. I just sort of went with that when I was writing the code implementation. I at least have this issue fixed, but have yet to push because I think JJ and Daryl are doing something with the code. I'll close this issue whenever I can make the next push. Thank you for your feedback.
