### ISSUE TITLE
T5-SI3: Gain an Understanding of the ProcessBuilder Class

### ISSUE THREAD

**Issue by Dorkatron199** [rsanchez-wsu/jfiles#92]
# T5-SI3: Gain an Understanding of the ProcessBuilder Class

Renamed from "<b>T5-M4-I3</b>"
Renamed from "<b>T5-M5-I3</b>"
Renamed from "<b>T5-M6-I3</b>"

This is a continuation from #64, which was in response to #35. This issue keeps getting passed onward and getting more and more specific in what needs to be done. Ideally, there may actually be some genuine progress on this issue in this milestone.
## What

We need a way to open files. No filesystem is complete without that functionality. To do that, the **`ProcessBuilder`** class needs to be used to create new processes. Furthermore, it has to be able to open applications with files as arguments. This issue will primarily focus on understanding how the class works. The objective of this issue is to learn how to use this class to open basic programs with files as arguments in windows. If we can learn it for one program in one system, we can most likely get it working on more advanced programs in other systems.
## Why

In order to achieve #64, the **`ProcessBuilder`** class needs to be used. This class supposedly takes in a list of string arguments and basically just runs them on the command line. This **1)** means that the application _can_ run on any OS, but **2)** means that it will be different fr each OS. From commit 52375a7, **`JFileManager`** already has a selection statement for Windows, Macintosh, and Linux. From eb38dd9, it is already in try/catch blocks. To move onward, these methods need to pass in commands into the **`ProcessBuilder`** class to start a file inside of a program. It should also be able to start a program without arguments of the user tries to start an application itself. This may be done through a separate command, due to the nature of such a method.
## How

The **`ProcessBuilder`** class is supposed to take the first argument as the actual command on the command line and all subsequent strings as arguments for that command. This **1)** means that any application we use to open a file needs to either **a)** be a command itself, or **b)** be ran as an argument in a run command and **2)** we will need to pass the file in as a string. The methodology by which the file is opened will change depending on the operating system, so someone who has a lot of knowledge of OSs will be of great use for this issue.
## Minimum Requirements

To close this issue, the individual in charge of this issue must at least have enough knowledge of the **`ProcessBuilder`** class to start a basic windows program, such as paint. It is preferable for this individual to be able to understand how to open a file in the application, but opening the program alone is enough for this issue to be closed. This is because I have no idea how hard this issue may be. It may go by quickly, it may be a bear to solve, I have no idea. If it turns out to be extremely simple, the individual assigned to this issue may start working on other OSs.
## Added Notes

We may want to expand the try/catch blocks to handle different issues differently to better log what is going on and better inform the user of what went wrong. For example, if the user tried to pass in something that is not a command for the OS, the issue may be different than if the application can't open that file. We may want the user to be able to select a new application to try and, no matter what the issue, we don't want the program to stop unless it absolutely has to. As or methods get developed more, so should our logging and exception-handling efforts.

**Comment by Dorkatron199** [comment]
## UPDATE:

<b><i>To anyone who is working on this issue:</i></b> This issue has been downgraded to a side-level issue. This issue should be pursued only after primary issues for the current milestone are complete.

If you wish to take this on as an issue for a milestone, let me know the week before so that I may put it on the milestone for you to work on it.

**Comment by Dorkatron199** [comment]
## NOTE:

Here is the link to the Java documentation for this class. [`ProcessBuilder`](http://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html)

**Comment by burks20** [comment]
New branch created.  I believe I have successfully implemented a command to use the ProcessBuilder library.  However, I did not want to merge it into Master yet, as it is just hard-coded to open MSPaint without accepting user input or implementing a hook into any other portion of jFiles to open a requested external application.  The feature can be added later, but the command has been implemented for now:   A new class called "ExtProcExec.java" has been added to src/edu/wright/cs/jfiles/commands.

**Comment by burks20** [comment]
Branch is  team8-dev-issue92

**Comment by burks20** [comment]
The class now accepts a String parameter for a directory/path to an external executable file.  Proper JavaDoc was added for usage.  This class does not extend the "Command" class like some of the other command files.

team8-dev-issue92 was merged to master.  I have deleted my branch and will be marking this issue closed.
