### ISSUE TITLE
Merge team 5 Jfiles work into team 2 work

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#94]
Merge team 5s dev branch into ours so that we  can proceed with Java bean work.  Specfically, getters and setters are specific to the contents of the object.  The jfile object is the base object used to send information from the server to the client.  We need to start work on this and need knowledge of the base object we intend to send.
### Completion Goal

Merge team5-dev and team2 into a new branch called team2/5-collab.
Make Travis ignore this new branch.

**Comment by rsanchez-wsu** [comment]
@bdenlinger Be careful about having slash (/) characters in Git branch names.  Git uses the slash to separate the remote name (origin in our case) from the branch name.  I would recommend `team-2-5-collab` in order to minimize confusion.

**Comment by Christofo** [comment]
I created the branch and merged team2 and team5-dev. 764496c5d29a98bcb5e66b38313a7105532c3e18

**Comment by Christofo** [comment]
@rsanchez-wsu Can you please disable Travis CI on this branch?

**Comment by rsanchez-wsu** [comment]
@Christofo I have Travis already configured to ignore branches that end in `-dev`.  The best thing would be to either rename the branch to something like `team-2-5-collab-dev`, or to go into `.travis.yml` on the branch and tweak it.  Have a look at the `.travis.yml` on your branch and see if you can add the necessary lines to have it ignore the branch if you like.  Feel free to ping me if you want for me to have a look at your proposed change before you push it.

**Comment by tytrip** [comment]
The branch was renamed to "team-2-5-dev" via commit d6eed61. I am closing this issue since the completion criteria has been met.

**Comment by rsanchez-wsu** [comment]
@tytrip Are you sure that the branch was renamed?  It looks to me like the team-2-5-collab branch is still in the repository.  If you meant to delete it, remember that there is a push operation involved in deleting a remote branch.

**Comment by tytrip** [comment]
@rsanchez-wsu you are correct, I created a new branch but didn't delete the original branch. The original branch named "team-2-5-collab" should now be deleted.

**Comment by rsanchez-wsu** [comment]
@tytrip It appears that the -collab branch has reappeared in the last few days.  Be aware that when you delete a branch, you need to also notify everyone that may have likely had it checked out (probably just people on your team) so that they can prune it from their local repositories.  Otherwise, every time someone that still has the branch does a full push (i.e., all branches), it will be pushed up to the remote again.
