### ISSUE TITLE
Fix issue with config file pathing

### ISSUE THREAD

**Issue by bdenlinger** [rsanchez-wsu/jfiles#95]
References #87.  Code committed to master contains a bug where environmental variables are not read correctly.  Specfically, values like $HOME and %APPDATA% are not understood as variables.  The correct procedure would be use [System.Properties](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html) class.
### Completion Goal

Config file is correctly read when stored in:
`$HOME/.jfiles/serverConfig.xml`

**Comment by tytrip** [comment]
Fixed via 530e3a9

**Comment by tytrip** [comment]
Correction: 530e2a9
