### ISSUE TITLE
Implement Default Folder / File Icons in Basic GUI Window

### ISSUE THREAD

**Issue by AlexDespain01** [rsanchez-wsu/jfiles#99]
As we have a basic GUI window that can parse XML and display clickable objects on the screen I believe the next step will be to begin changing this to clickable transparent folder and file icons.

Once a default folder and file icon are created, we will need a way to display these on the screen. They need to remain clickable as well so that a click will correspond to opening a file or folder.

This may require collaboration with Team 6 (Issue #82).

**Comment by AlexDespain01** [comment]
We can then later begin producing icons for different file types (i.e. .xls, .docx, .png, etc)

**Comment by randymusser** [comment]
File and folder icons have been implemented into the gui.
